### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#1]
Right now, we're building the errors manually in many places, which is error-prone and leads to a lot of duplicated code.

It would be great to add methods to deal with error creation, such as:

```js
const { organizationInvitationsOrgNotFound } = require('../error');
throw organizationInvitationsOrgNotFound(invitation.organizationId);
```

which internally, it would be something like:

```js
class HubError extends Error {
  static organizationInvitationsOrgNotFound(orgId) {
    return new HubError({
      ...
    });
  }
}
```

**Comment by magicmatatjahu** [comment]
Due to the fact that we are implementing Studio from "scratch", I am closing this issue.
