### ISSUE TITLE
Enhance the Visual JSON Schema Editor 

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#1023]
After merging: https://github.com/asyncapi/studio/pull/905
The visual editor needs to be enhanced for production

## Scope
- [ ] Look & Feel
- [ ] Deletion
- [ ] Nested objects
- [ ] Test functionality

## Complexity
Medium

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q2`, `bounty/medium`, `bounty/coding`
First assignment to third-party contributors: [2024-03-22 00:00:00 UTC+12:00](https://time.lol/#2024-03-22T00:00:00+12:00)
End Of Life: [2024-08-31 23:59:59 UTC-12:00](https://time.lol/#2024-08-31T23:59:59-12:00)

@asyncapi/bounty_team

**Comment by koukama** [comment]
I can work on this issue ?

**Comment by aeworxet** [comment]
@koukama
Please specify your real name in your GitHub profile as per your passport/ID before participating in the Bounty Program, as it will be compared to the `Legal Name` / `Full name of the account holder` during the payout.
https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR186

**Comment by Amzani** [comment]
As @princerajpoot20 is currently busy and you seem interested in continuing his work please go ahead @koukama. In case you need more context feel free to coordinate with @princerajpoot20.

**Comment by utnim2** [comment]
@princerajpoot20 i will like to work on it if no one is working on it.
Thanks

**Comment by princerajpoot20** [comment]
@utnim2 Please go ahead.

**Comment by princerajpoot20** [comment]
### Details about the Tasks

#### Things to Implement

- Delete Property Function
- Toggle Required/NotRequired Function
- Change Type of Property Function
- Add Property function, but only for cases which have a path containing `array<object>`.
- UI look and feel according to the Figma design.

#### Some minor fixes:

- When a property is of the type `array`, the data type of the array is not displayed in the visual editor.

**Comment by princerajpoot20** [comment]
@utnim2 Let me know if you need any help.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2024-04-02                 |[2024-04-08](https://time.lol/#2024-04-08T00:00:00+12:00)              |**[2024-05-17](https://time.lol/#2024-05-17T23:59:59-12:00)**        |[2024-04-19](https://time.lol/#2024-04-19T23:59:59-12:00)         |[2024-05-03](https://time.lol/#2024-05-03T23:59:59-12:00)         |**[2024-05-17](https://time.lol/#2024-05-17T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by utnim2** [comment]
> @utnim2 Let me know if you need any help.

Hey @princerajpoot20 the figma link is broken in #748

**Comment by KhudaDad414** [comment]
@utnim2 the link is Ok. I think something is wrong with Figma. first login Figma and then clink on that link. it should work. If that didn't help, you can try using [this link](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&mode=design&t=FuwOpW3CmJwJgygL-1)

**Comment by aeworxet** [comment]
https://github.com/asyncapi/studio/pull/1065#issuecomment-2083300317

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/studio/pull/1065#issuecomment-2083300317) (@utnim2), all remaining target dates of the Bounty Issue's Timeline are extended by one calendar week.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2024-04-02                 |[2024-04-08](https://time.lol/#2024-04-08T00:00:00+12:00)              |**[2024-05-24](https://time.lol/#2024-05-24T23:59:59-12:00)**        |[2024-04-19](https://time.lol/#2024-04-19T23:59:59-12:00)         |[2024-05-10](https://time.lol/#2024-05-10T23:59:59-12:00)         |**[2024-05-24](https://time.lol/#2024-05-24T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by aeworxet** [comment]
@Bhavyajain21 
![image](https://github.com/asyncapi/studio/assets/16149591/860efe86-2c5a-4a87-b84c-80b31605f01f)

**Comment by aeworxet** [comment]
@Bhavyajain21 
![image](https://github.com/asyncapi/studio/assets/16149591/e5198710-a3a5-4247-9d63-151472f936a2)

**Comment by princerajpoot20** [comment]
@aeworxet  Could you please extend the deadline by two weeks? There are some changes left to be implemented. 
Thank you for the consideration. 🙂
cc: @Gmin2

**Comment by aeworxet** [comment]
Upon [request of the AsyncAPI Maintainer](https://github.com/asyncapi/studio/issues/1023#issuecomment-2140443407), who is currently leading the development (@princerajpoot20), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2024-04-02                 |[2024-04-08](https://time.lol/#2024-04-08T00:00:00+12:00)              |**[2024-06-07](https://time.lol/#2024-06-07T23:59:59-12:00)**        |[2024-04-19](https://time.lol/#2024-04-19T23:59:59-12:00)         |[2024-05-10](https://time.lol/#2024-05-10T23:59:59-12:00)         |**[2024-06-07](https://time.lol/#2024-06-07T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by Amzani** [comment]
Accepted as done

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

@Gmin2, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty studio#1023`, tag `bounty`, and full URL of this Bounty Issue in the description.

**Comment by aeworxet** [comment]
@Bhavyajain21 

There is a [Slack Workspace](https://asyncapi.com/slack-invite).
You can find most people in it by their GitHub handles or names.
