### ISSUE TITLE
Fix linting issues in studio-next

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#1029]
Fix Linting issues

<img width="1366" alt="Screenshot 2024-03-20 at 09 13 32" src="https://github.com/asyncapi/studio/assets/554438/9c01abdc-91ef-46ec-9272-160c18091e7e">

**Comment by helios2003** [comment]
Is ``props`` going to be used in the future in the file?

**Comment by Amzani** [comment]
cc @Shurtu-gal

**Comment by helios2003** [comment]
Thanks for the reply @Shurtu-gal. I have opened up a PR to resolve the issue.
