### ISSUE TITLE
The html on the preview uses a newer version of the generator tool than the one used in the "generate code/docs" section.

### ISSUE THREAD

**Issue by ghuser** [asyncapi/studio#1031]
#### Describe the bug
Recently I have reported  [avro-schema-parser#240](https://github.com/asyncapi/avro-schema-parser/issues/240) that was fixed, and I can see the fix being reflected to [studio.asyncapi.com](https://studio.asyncapi.com/). 

However when I click on "Generate code/docs" and select the "html website" (with option singleFile enabled) the generated code does not include the fix.

#### How to Reproduce

Paste the document below into studio.asyncapi.com and see that the required option is presented in all r1,r2,r3 properties. This implies that the fix described in [avro-schema-parser#240](https://github.com/asyncapi/avro-schema-parser/issues/240) has been applied.

```yml
asyncapi: 2.6.0
info:
  title: AsyncAPI
  version: 1.0.0
  description: AsyncAPI
channels:
  example:
    publish:
      message:
        $ref: '#/components/messages/example_message'
components:
  messages:
    example_message:
      name: example_event
      schemaFormat: application/vnd.apache.avro;version=1.9.0
      payload:
        type: record
        name: ParentRecord
        fields:
          - name: r1
            type:
              type: enum
              name: MyEnum
              symbols:
                - A
                - B
                - C
          - name: r2
            type: MyEnum
          - name: r3
            type: MyEnum
```

Now try the option:  "Generate code/docs" -> "html website" (with option singleFile enabled). If you preview the generated html you will see that only r1 is presented as required. This means that the fix described in [avro-schema-parser#240](https://github.com/asyncapi/avro-schema-parser/issues/240) has not been applied.

#### Expected behavior

The html in preview and the generated html should be the same.

**Comment by KhudaDad414** [comment]
I think the problem is that the [html-template](https://github.com/asyncapi/html-template)'s parser-js is not updated. I've put up a PR and let's see if that fixes the issue.

**Comment by ghuser** [comment]
@KhudaDad414 The issue is still present on the exported html (using the example provided in this ticket)

**Comment by KhudaDad414** [comment]
@ghuser it will applied after we merge this PR: https://github.com/asyncapi/studio/pull/1038

**Comment by ghuser** [comment]
> @ghuser it will applied after we merge this PR: https://github.com/asyncapi/studio/pull/1038

@KhudaDad414 The issue is still there. Preview works. Exported html (single file) does not.

**Comment by ghuser** [comment]
This issue has not yet been resolved. Please test the given input. You will see that on the exported version of the page the required label only appears on the first field. This does not happen on the preview page.
