### ISSUE TITLE
Github link should redirect to asyncapi studio repo instead of async api org link

### ISSUE THREAD

**Issue by sahilkumar003** [asyncapi/studio#1100]
#### Describe the bug
Github link redirects to asyncapi org github page

#### How to Reproduce
Click the github icon on the website

#### Expected behavior
Github link should redirect to asyncapi studio repo instead of org page link

**Comment by NewMayur** [comment]
@Amzani I'm interested in working on this. Can I work?

**Comment by princerajpoot20** [comment]
Closing this issue as it has already been resolved with #1102
