### ISSUE TITLE
Merge the `studio-next` and `studio` apps

### ISSUE THREAD

**Issue by Shurtu-gal** [asyncapi/studio#1134]
The studio-next folder was created for migrating to next.js. As the migration is complete now, it is time to remove the studio folder to decrease the redundancy.

Steps:
- Remove the studio folder.
- Check if there are any regressive problems or differences in the studio-next app as compared to the currently deployed site.
- @fmvilas I suppose we will have to edit the domain tracking at netlify as well.

**Comment by aeworxet** [comment]
Please do this task only after https://github.com/asyncapi/studio/pull/1094 is merged.

Besides, special attention must be paid to paths, naming, and versioning:
https://github.com/asyncapi/studio/blob/master/apps/studio/package.json#L2
https://github.com/asyncapi/studio/blob/master/apps/studio-next/package.json#L2

**Comment by Shurtu-gal** [comment]
> Please do this task only after https://github.com/asyncapi/studio/pull/1094 is merged.

Sure. Just wanted to initiate it before we move along.

**Comment by aeworxet** [comment]
The migrated version also might get immediately broken due to https://github.com/asyncapi/studio/pull/1094#issuecomment-2344700719.

**Comment by aeworxet** [comment]
https://github.com/asyncapi/studio/pull/1094 was merged, so pay attention to this change: https://github.com/asyncapi/studio/pull/1094#issuecomment-2344700719.

**Comment by aeworxet** [comment]
FYI
[Hard-locked](https://github.com/asyncapi/studio/pull/1139) the `@asyncapi/converter` on version `1.5.0` during handling incident https://github.com/asyncapi/studio/issues/1138.

**Comment by aeworxet** [comment]
https://github.com/asyncapi/studio/pull/1120 was merged just now.

**Comment by prashantrai-30** [comment]
Hey @Shurtu-gal,can you assign this to me.

**Comment by Shurtu-gal** [comment]
Hey @prashantrai-30 already a PR has resolved this. I forgot to close this.
