### ISSUE TITLE
Some (awesome) docs for the new Studio

### ISSUE THREAD

**Issue by boyney123** [asyncapi/studio#129]
#### Reason/Context

@magicmatatjahu has been working hard on getting our new studio up and running, and it's looks amazing.

With the ideas we have coming to this application will grow with features and functionality.

I think we might want to accompany this application with some nice docs 👀

I just come across this website https://developers.apideck.com/ and something like this would be great for our Studio (I think).

A place people can find
- How to install it
- What features it provides etc

Think it would be great!

Any thoughts? cc: @magicmatatjahu @alequetzalli

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by magicmatatjahu** [comment]
@nawed2611 

At the moment we do not know what is to be included in such documentation, so I do not know if there is any point in you taking on this task.
