### ISSUE TITLE
Create a Google Analytics plugin

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#14]
### Description

We used to have Google Analytics hardcoded (see #13). However, some people may not want to use it so it's better if we make it a plugin instead.

### Implementation suggestion

1. Go to `src/pages/_app.js` file and make it trigger a new kind of event on the `render` function. For instance, something like a `page:render` event. Make sure this event is only triggered on the client-side render.
2. Make the plugin subscribe to the event and trigger an `initialize` and `pageview` call when a new event comes in.

### Hints

The code for triggering/subscribing to events is on `src/lib/events.js`. However, this library was created for the backend and it imports the `config` lib, which may contain secrets. If we use the `events` lib on the frontend, these secrets may be exposed on the browser. Watch out!

**Comment by AceTheCreator** [comment]
Hi, @fmvilas I'd really love to contribute and help with the development of the studio. I'd love to start by fixing current open issues. and is there a slack group for the ongoing development of the studio?

**Comment by fmvilas** [comment]
Hey! Sure, you can join us at asyncapi.com/slack-invite. There's a #tooling channel there. Thanks!

**Comment by AceTheCreator** [comment]
@fmvilas When the page renders, should there be a popup that asks if users want to enable google analytics? And also developers can manually enable/disable the plugin from the codebase.

**Comment by fmvilas** [comment]
Yeah, the way to configure the plugins you want to load is to edit this file here: https://github.com/asyncapi/studio/blob/master/config/plugins.json.

**Comment by AceTheCreator** [comment]
@fmvilas Can i change the _app.js to a functional component? or is there a specific reason why you're using class component?

**Comment by fmvilas** [comment]
No problem. Feel free to change it.

**Comment by AceTheCreator** [comment]
@fmvilas I'm having issue with plugin path after adding a plugin to the plugins.json file. 
on the left panel is the error message i'm getting when loading a plugin. Note: the plugin successfully loaded but after i get this message. Any idea how to fix it?
![download (1)](https://user-images.githubusercontent.com/40604284/114417475-89e1ff80-9ba9-11eb-9536-fc5ced80ff5e.png)

**Comment by AceTheCreator** [comment]
> @fmvilas I'm having issue with plugin path after adding a plugin to the plugins.json file.
> on the left panel is the error message i'm getting when loading a plugin. Note: the plugin successfully loaded but after i get this message. Any idea how to fix it?

In the plugins.json file i just pass it like this `{ plugins: ['path to plugin folder', ... ] }` I'm i doing something wrong?

**Comment by fmvilas** [comment]
mmmm not sure. Can you push a PR so I can try myself?

**Comment by AceTheCreator** [comment]
@fmvilas try using the existing code by adding sentry path to the list of plugins in the `plugins.json` file and see.

**Comment by fmvilas** [comment]
Oh! I know what's happening. Plugins are **always** loaded from `node_modules`. So if you try to load `./plugins/google-analytics` it's going to try to load `node_modules/plugins/google-analytics`. The best way to overcome this during development is to link the module like this:

```bash
cd plugins/google-analytics
## Make sure the package name and version are correct. Something like `@asyncapistudio/plugin-google-analytics` and version `0.1.0` or whatever you prefer.
npm link
```

Then go back to the project root directory and tell it you want to use the linked package:

```bash
cd ../.. # Back to project root dir
npm link @asyncapistudio/plugin-google-analytics # or the package name you chose
```

And now on the plugins.json file, you have to specify it like this:

```json
{
  "plugins": [
    "@asyncapistudio/plugin-google-analytics"
  ]
}
```

Hope that makes sense :)

**Comment by AceTheCreator** [comment]
> Oh! I know what's happening. Plugins are **always** loaded from `node_modules`. So if you try to load `./plugins/google-analytics` it's going to try to load `node_modules/plugins/google-analytics`. The best way to overcome this during development is to link the module like this:
> 
> ```shell
> cd plugins/google-analytics
> ## Make sure the package name and version are correct. Something like `@asyncapistudio/plugin-google-analytics` and version `0.1.0` or whatever you prefer.
> npm link
> ```
> 
> Then go back to the project root directory and tell it you want to use the linked package:
> 
> ```shell
> cd ../.. # Back to project root dir
> npm link @asyncapistudio/plugin-google-analytics # or the package name you chose
> ```
> 
> And now on the plugins.json file, you have to specify it like this:
> 
> ```json
> {
>   "plugins": [
>     "@asyncapistudio/plugin-google-analytics"
>   ]
> }
> ```
> 
> Hope that makes sense :)

Yeah it makes sense . One more thing @fmvilas  how do i make the plugin subscribe to an event on page render?

**Comment by AceTheCreator** [comment]
@fmvilas is the event.on for subscribing and event.emit for triggering?

**Comment by fmvilas** [comment]
Yes! But you probably will have to emit the event yourself when a page is rendered. And also subscribe on the plugin side, of course.

I recommend you to have a look at the Node.js [EventEmitter](https://nodejs.org/api/events.html), which is what we're using right now.

**Comment by AceTheCreator** [comment]
Ok I'll have a look at it.
When i import the event to ._app.js i get an error requiring fs which i was able to overcome by ignoring npm packages that depend on `fs` module. But after that i get this error relating to .env
![download (2)](https://user-images.githubusercontent.com/40604284/114780498-64065780-9d6f-11eb-9345-8832a4d0264e.png)

**Comment by AceTheCreator** [comment]
> Ok I'll have a look at it.
> When i import the event to ._app.js i get an error requiring fs which i was able to overcome by ignoring npm packages that depend on `fs` module. But after that i get this error relating to .env
> ![download (2)](https://user-images.githubusercontent.com/40604284/114780498-64065780-9d6f-11eb-9345-8832a4d0264e.png)

I tried ignoring it but it seems it has something to do with the overrideWithEnvVars function in the lib which i know is specific for server side. Any idea how i can overcome this?

**Comment by AceTheCreator** [comment]
> > Ok I'll have a look at it.
> > When i import the event to ._app.js i get an error requiring fs which i was able to overcome by ignoring npm packages that depend on `fs` module. But after that i get this error relating to .env
> > ![download (2)](https://user-images.githubusercontent.com/40604284/114780498-64065780-9d6f-11eb-9345-8832a4d0264e.png)
> 
> I tried ignoring it but it seems it has something to do with the overrideWithEnvVars function in the lib which i know is specific for server side. Any idea how i can overcome this?

@fmvilas I was able to resolve this problem, so don't worry looking into it.

**Comment by AceTheCreator** [comment]
@fmvilas How do i make the plugin subscribe to the event? I already define a `page:render` event on the plugin's `package.json`, how do i get to use this event? I'm kinda confuse.

**Comment by fmvilas** [comment]
Oh, I completely missed your messages above. Glad you were able to solve it. Bear in mind that `_app.js` is a file that executes on the server first and then again on the browser, so nothing backend-related can be imported there, especially environment variables which may contain secrets.

That means you'll have to create an eventing system for the front end. Something like [this](https://github.com/asyncapi/studio/blob/master/src/lib/events.js) but only imported in frontend.

**Comment by AceTheCreator** [comment]
> Oh, I completely missed your messages above. Glad you were able to solve it. Bear in mind that `_app.js` is a file that executes on the server first and then again on the browser, so nothing backend-related can be imported there, especially environment variables which may contain secrets.
> 
> That means you'll have to create an eventing system for the front end. Something like [this](https://github.com/asyncapi/studio/blob/master/src/lib/events.js) but only imported in frontend.

Ok I'll do that. But how can i make the plugin subscribe to an event?

**Comment by AceTheCreator** [comment]
How do i make use of this plugin code below in the app. 
![download (3)](https://user-images.githubusercontent.com/40604284/115041176-21a55d80-9eca-11eb-8905-49dda15c864a.png)

**Comment by AceTheCreator** [comment]
@fmvilas I'm trying to make the plugin subscribe to the `page:render` event. On page render i emit the the event, will i also have to import the plugin in the `_app.js` file and listen for the event and trigger the plugin cuz i'm quite confuse 😶‍🌫️. Should i open a draft PR? So that you can point me to the right direction

**Comment by fmvilas** [comment]
Yeah, I think that's the best way.

**Comment by AceTheCreator** [comment]
> ### Description
> We used to have Google Analytics hardcoded (see #13). However, some people may not want to use it so it's better if we make it a plugin instead.
> 
> ### Implementation suggestion
> 1. Go to `src/pages/_app.js` file and make it trigger a new kind of event on the `render` function. For instance, something like a `page:render` event. Make sure this event is only triggered on the client-side render.
> 2. Make the plugin subscribe to the event and trigger an `initialize` and `pageview` call when a new event comes in.
> 
> ### Hints
> The code for triggering/subscribing to events is on `src/lib/events.js`. However, this library was created for the backend and it imports the `config` lib, which may contain secrets. If we use the `events` lib on the frontend, these secrets may be exposed on the browser. Watch out!

@fmvilas when I subscribe to the event from a different file and I trigger it in the app.js render it doesn't work. For instance, when I call event names from the app.js to check the list of subscribed events, it returns an empty array. Except I call both the subscribe and trigger event within the page render function in the app.js
@fmvilas please check out my updated draft PR

**Comment by AceTheCreator** [comment]
> ### Description
> We used to have Google Analytics hardcoded (see #13). However, some people may not want to use it so it's better if we make it a plugin instead.
> 
> ### Implementation suggestion
> 1. Go to `src/pages/_app.js` file and make it trigger a new kind of event on the `render` function. For instance, something like a `page:render` event. Make sure this event is only triggered on the client-side render.
> 2. Make the plugin subscribe to the event and trigger an `initialize` and `pageview` call when a new event comes in.
> 
> ### Hints
> The code for triggering/subscribing to events is on `src/lib/events.js`. However, this library was created for the backend and it imports the `config` lib, which may contain secrets. If we use the `events` lib on the frontend, these secrets may be exposed on the browser. Watch out!

@fmvilas when I subscribe to the event from a different file and I trigger it in the app.js render it doesn't work. For instance, when I call event names from the app.js to check the list of subscribed events, it returns an empty array. Except I call both the subscribe and trigger event within the page render function in the app.js
@fmvilas please check out my updated draft PR

**Comment by fmvilas** [comment]
@magicmatatjahu can you have a look? I really don't have much time to dig into code 😓 👶 🍼

**Comment by magicmatatjahu** [comment]
@AceTheCreator I answered in the PR :)

I know @fmvilas that you are very busy, but please, in the free time, check my comment, because (probably) we cannot use plugins on the client side. More info is in comment. Maybe you had this case in mind when you wrote issue's description, so let us know 😅

**Comment by magicmatatjahu** [comment]
Since we're going with a different implementation of Studio (as a SPA app, rather than using NextJS) I'm closing this issue. In addition, the implementation of the current plugins works only on NodeJS and not in the browser (#37 (comment)), so we have to redefine them - probably have two types, for the frontend (asyncapi/asyncapi-react#433) and backend (#86).
