### ISSUE TITLE
For new users give them the ability to select a template file (or real world example)

### ISSUE THREAD

**Issue by boyney123** [asyncapi/studio#147]
#### Reason/Context

The studio is now [hosted](studio.asyncapi.com) on the internet which is great!

People will be coming to this from all over, and I wonder if it would be a nice feature for them to select a template or real-world example before they go into the studio.

I made a video to explain what I mean and also how it would kinda work (https://asyncapi.slack.com/files/U020GN9C6FM/F02KDGTE1L2/studioexamples.mp4)

**Screenshot**

![image](https://user-images.githubusercontent.com/3268013/139269271-1037e48e-4424-4335-ae93-37c053c311bf.png)

**When will it be shown**

- When users come new to the studio
- When users come from the web (maybe).

## Why we need this?

I just think it would give users the ability to explore AsyncAPI more, rather than be thrown a default template on load.

**Comment by boyney123** [comment]
> How did you do that? Did you eject cra config for webpack?

I'm using [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) which allows you to keep everything as is and extend the configs etc, only other option is to eject as you said.... create-react-app is quite locked down like that

> What I wonder most is whether we actually need a /new path (and router). If we really need paths then maybe we should go in the direction of slide-over like in TailwindCSS (tailwindui.com/components/application-ui/overlays/slide-overs) rather than a new page and then combine slide-over with the new path in the sense that the user has the new path in the browser url but sees the editor and sidebar which are dimmed, like in a modal - very similar solution to Instagram when you open some picture, then browser url has changed but you still see another pictures but in background

Yeah hard to tell really, only reason for the new page is to keep some kind of flow for example:

1. Pick your protocol / example to see
2. Load the editor

I worry about too much going on, if the editor is in background with slideover etc, but happy to try it too.

> Btw. awesome implementation :) I very like it, but yeah, we should discuss in which direction we should go:

Yeah definitely, I'm going to raise what I have done as a draft PR (hopefully get a preview link with that), and also quickly work on the VSCode page you had the idea for (with a draft PR) and I will bring it back to the community with some options to see where we head / decide.

What do you think?

**Comment by magicmatatjahu** [comment]
Implemented by https://github.com/asyncapi/studio/pull/158 and https://github.com/asyncapi/studio/pull/201

@boyney123 If you think that we should leave it open, please write why and of course reopen it :)
