### ISSUE TITLE
Create og:image meta image design

### ISSUE THREAD

**Issue by mcturco** [asyncapi/studio#149]
http://studio.asyncapi.com/

**Examples:**
![](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fmaster--asyncapi-website.netlify.app%2Fimg%2Fsocial%2Fcard.png)

![](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fmaster--asyncapi-website.netlify.app%2Fimg%2Fsocial%2Fgenerator.png)

**Comment by mcturco** [comment]
@boyney123 See attached for the requested Open Graph image for AsyncAPI studio! Let me know if this works or if I should make any adjustments. Thanks!

<img width="1826" alt="AsyncAPIStudio_OGImage" src="https://user-images.githubusercontent.com/60163079/139488681-ab846435-e8cd-4acb-9364-e5f8ef354e71.png">

**Comment by boyney123** [comment]
Thanks @mcturco LGTM!

Will raise an issue on Studio to get this open graph in

**Comment by magicmatatjahu** [comment]
@mcturco Hello! Do you want to add this image to the studio, like on the conference website, or do you want someone from us to do it?

**Comment by mcturco** [comment]
@magicmatatjahu I don't mind adding it! I can do that now and then submit a PR 😄

**Comment by magicmatatjahu** [comment]
@mcturco Sure, there is a main index.html - https://github.com/asyncapi/studio/blob/master/public/index.html :) If you will have any problems, please write about them.
