### ISSUE TITLE
AsyncAPI freezes on Firefox

### ISSUE THREAD

**Issue by fkromer** [asyncapi/studio#171]
#### Describe the bug

The [hosted AsyncAPI studio website](https://studio.asyncapi.com) freezes regularly when editing AsyncAPI .yaml files. If the website recovers from freeze the default yaml file is loaded. The current WA is to store the edited file into a local yaml file every few seconds. Of course this is quite annoying. Actually this makes it impossible to use the website ATM.

#### How to Reproduce

Open https://studio.asyncapi.com in Firefox and edit a file with approx. 100 lines.

![image](https://user-images.githubusercontent.com/10199742/140558625-531eca4c-cc73-4d8a-9713-f24750585f60.png)

**Comment by magicmatatjahu** [comment]
@fkromer Hi, thanks for the issue! What do you mean by:

> The current WA is to store the edited file into a local yaml file every few seconds. Of course this is quite annoying.

What is `WA` abbreviation? And what do you mean by local yaml file? Do you use the CLI integration with Studio https://github.com/asyncapi/cli/pull/102? Of course it is no argument but for me only when I paste this specification https://raw.githubusercontent.com/asyncapi/modelina/master/test/blackbox/docs/AsyncAPI-2_0/zbos_mqtt-all-asyncapi.json the Studio needs some time to update the html preview. For 100 lines specification everything works without any problem (I mean Studio without CLI integration) - I tested on Firefox and Chrome.

**Comment by tobi6112** [comment]
I think by `WA` is workaround ment. 

However, I can confirm the issue in MS Edge 95.0.1020.44 on Windows 11. It seems to be some kind of Memleak. I'm trying to reproduce it in detail and give you more information when I have the spare time to do so. 

But as of now I can say, that in my case I was editing nested component schemas, when the UI slowly went into freezing until the browser tab itself was not responding anymore and detected by the chrome task manager.

**Comment by magicmatatjahu** [comment]
Ok, I checked and it's true that the longer you use the Studio, the faster the stackoverflow for a single browser tab occurs. I created PR for fixing problem on the parserJS side https://github.com/asyncapi/parser-js/pull/406 but there is still places to improve. We cannot "decrease" size of rendered content, but we can change the rendering from automatic to manual, that is, when the user presses the appropriate button for rendering - this will limit the memory consumption on the rendering side of the component. It will be possible to switch between automatic and manual rendering. What do you guys think?

**Comment by tobi6112** [comment]
@magicmatatjahu That's great to hear. Wouldn't it be sufficient to introduce a debounce time? For example to render the page if within 2 seconds no change in the spec occurred.

Personally I don't think that a manual rendering is not the way to go and not a proper solution for this problem. But in return a user-option for enabling manual rendering might be a nice feature.

**Comment by magicmatatjahu** [comment]
We have debounce, at the moment 250ms, I can increase that to 1s but there is still problem with huge spec for old devices. I have very good computer so for me rendering even 10x per row isn't problem, but for someone it can be. Thanks for response!

**Comment by fkromer** [comment]
@magicmatatjahu The editing of my spec file in studio works fine on firefox right now.
