### ISSUE TITLE
When clicking on items in the side bar (messages, operations, schema etc) be nice to highlight the nodes in the flow diagram

### ISSUE THREAD

**Issue by boyney123** [asyncapi/studio#182]
#### Reason/Context

At the moment when you have the sidebar and the documentation open, clicking on a message, operation etc will take you straight to the place in the docs.

I think it would be a nice touch to have the nodes in the flow diagram highlight (maybe blink animate) when clicking on these nav items.

So if the user has  this nav bar open....
![image](https://user-images.githubusercontent.com/3268013/142776844-22cfe577-5c72-4a58-a1a3-ce8c30ade251.png)

Clicking on the items whilst looking at the flow diagram will highlight the nodes.

**Comment by nawed2611** [comment]
Can I take up this issue?

**Comment by Ankitchaudharyy** [comment]
Hey @boyney123, @magicmatatjahu!,
I can work on this issue. Please assign this to me.

**Comment by magicmatatjahu** [comment]
@Ankitchaudharyy You can :)
