### ISSUE TITLE
Add tooltips to navigation and icons to new examples screen

### ISSUE THREAD

**Issue by mcturco** [asyncapi/studio#193]
#### Reason/Context
I am wondering if the icons on the navigation properly explain what the window is that corresponds to it. I suppose users who are frequent on the studio might know from learning the system, but in order to make it easier for new users to quickly understand the system, I am proposing that we add tooltips on hover of each navigation item so there are proper labels for each window pane.

I think in addition to this, there might be a way where we can make the navigation items that are active have a more obvious style than just the white color and border on the left side. I feel that sometimes the white border on the left can get lost depending on where you have your window positioned on your computer, especially because someone may have the window bleeding off the left side and might miss the white border entirely.

I can create a mock up for these ideas soon and share it on this issue, but just wanted to add in this issue ASAP.

**Comment by magicmatatjahu** [comment]
@mcturco Thanks for ideas, I like them! Regarding to the color of the active nav items, we can change left white border to the pink (this color of `studio` title) and also make more contrast, I'm thinking of brightening up the background of nav item. I will wait anyway for your mocks :)

**Comment by boyney123** [comment]
`I am proposing that we add tooltips on hover of each navigation item so there are proper labels for each window pane.`

💯 , think maybe we can also add #199 here too?
