### ISSUE TITLE
Templates section button does not trigger events for closing or opening previous tabs

### ISSUE THREAD

**Issue by smoya** [asyncapi/studio#198]
#### Describe the bug
Unlike the events visualizer button, clicking on the new templates button opens a new view that covers the whole studio (except the nav bar). When clicking then on any other button like the code one ![CleanShot 2021-12-02 at 12 31 41](https://user-images.githubusercontent.com/1083296/144414192-dcd35aa1-cfdb-49d3-9a52-bf363ced31e4.png), doesn't quit the examples view.

The only way to close it is to click again on the same examples button, which is not a 100% expected behavior because it is quite inconsistent with the rest.

#### How to Reproduce
See the following video:

https://user-images.githubusercontent.com/1083296/144412090-a9f801b4-171d-4848-b17a-ec54f90cb8fd.mp4

#### Expected behavior
Either examples view shows as a popup, or either just as a side view (as the events visualizer, code examples, etc), or we improve the navigation so on any click in any button will close the examples view.

**Comment by magicmatatjahu** [comment]
> Either examples view shows as a popup, or either just as a side view (as the events visualizer, code examples, etc), or we improve the navigation so on any click in any button will close the examples view.

The question is which would be better? From a UX standpoint, I think modal, @mcturco @boyney123 any thoughts? 🤔

**Comment by mcturco** [comment]
@magicmatatjahu Agreed! I think a modal for the new templates will work just fine. So then the modal should close if you click a different nav item on the left side, as @smoya pointed out, good catch!

**Comment by magicmatatjahu** [comment]
Nope, no close by clicking on the nav item. It will be similar to normal modal like:

![image](https://user-images.githubusercontent.com/20404945/144632587-b736b3aa-2745-49dc-b44d-e2666b060acd.png)

But content will be templates :) And then you cannot click on the nav - you can try.

**Comment by mcturco** [comment]
@magicmatatjahu Oh! Gotcha. Yes that works too!

**Comment by boyney123** [comment]
Yeah modal sounds good to me! Nice catch @smoya

**Comment by boyney123** [comment]
I can try and pick this up 👍

**Comment by boyney123** [comment]
Think it's fixed in #201

**Comment by magicmatatjahu** [comment]
Fixed in the https://github.com/asyncapi/studio/pull/201
