### ISSUE TITLE
Accessibility: Make buttons on left nav bar accessible to screen readers

### ISSUE THREAD

**Issue by smoya** [asyncapi/studio#199]
#### Reason/Context
![Studio left nav bar](https://user-images.githubusercontent.com/1083296/144414684-4c1035b9-9c1f-4988-b50e-1b4ba3ade531.png)

Current nav bar buttons don't provide any alternative text. This makes it hard to know what button does what.
The issue goes further because it means screen readers won't do their job, meaning Studio can't be used on all its potential by people with visual impairments. 

#### Description
I would suggest we, at least, add both `<title>` and `<desc>` elements to our inline svg's (the buttons are) so they act as alternative text.

More info here https://css-tricks.com/accessible-svgs/

**Comment by boyney123** [comment]
Nice one @smoya 

Also I think it would be nice to add tooltips for the icons, most vertical nav / code-based systems I have used in the past have these. Think it's a small change that can help people understand what the icons do.

Codesandbox example 👇

![image](https://user-images.githubusercontent.com/3268013/144819971-53812ed0-2360-409e-a6c5-c9f3628fa40e.png)

**Comment by boyney123** [comment]
Ah looks like @mcturco has already opened up and issue for it :) #193

**Comment by mcturco** [comment]
@boyney123 yes!! Your suggestion here was exactly what I was thinking for #193 :)))

**Comment by mcturco** [comment]
Finally began working on a solution for this (the stale label reminded me of this idea! 😄)

## Prototype
Here is a video walkthrough of how we can implement this into Studio
https://www.loom.com/share/0ec2e978b93146b7a99da2d3aa6496c9

And here is the figma prototype link if you would like to view it on your own:
https://www.figma.com/proto/FfxMJnvJLpHpAHueKthzxe/Add-tooltips-to-side-navigation?node-id=2%3A386&scaling=min-zoom&page-id=2%3A30

## Components
<img width="1064" alt="Screen Shot 2022-08-05 at 1 20 08 PM" src="https://user-images.githubusercontent.com/60163079/183129320-252e3197-c997-4a45-9eab-6981900aa981.png">

### 1. Current nav buttons
We will be adding a background on hover to each nav button. The specs of this are as follows:

- margin: 8px
- padding: 8px
- border-radius: 4px
- background-color: `bg-gray-600`

<img width="1022" alt="Screen Shot 2022-08-05 at 1 26 53 PM" src="https://user-images.githubusercontent.com/60163079/183129683-f9cc50f1-e974-43e1-8043-ab6d7d1fe1bf.png">

<img width="1012" alt="Screen Shot 2022-08-05 at 1 28 11 PM" src="https://user-images.githubusercontent.com/60163079/183130074-e09cbf1f-03a2-4a57-bcda-ded0cf36ccfb.png">


### 2. *New* Tooltip component
This new tool tip component should fade in on hover of each navigation item. The design specs for this new component are as follows:

- border-radius: 4px
- background-color: `bg-gray-600`
- padding: 4px 8px
- text color: `white`
- font-family: Inter
- font-size: 12px
- font-weight: 400
- margin-left: 8px from sidebar edge

<img width="682" alt="Screen Shot 2022-08-05 at 1 35 30 PM" src="https://user-images.githubusercontent.com/60163079/183130877-49e80fda-7118-4686-81d8-e3b4b705dc27.png">

---

Let me know what everyone thinks about this and if we should start implementing it in a PR! 

cc: @smoya @magicmatatjahu

**Comment by smoya** [comment]
I like this new design, I feel it fixes the issue totally 💯 .

Just a small comment, is the hover animation for the tooltips that figma shows part of the final design? I feel it so slow that confuses me some times, having two tooltips being showed at the same time.

**Comment by mcturco** [comment]
> I like this new design, I feel it fixes the issue totally 💯 .
> 
> Just a small comment, is the hover animation for the tooltips that figma shows part of the final design? I feel it so slow that confuses me some times, having two tooltips being showed at the same time.

Thanks, @smoya! I definitely think we can speed up the animation duration. I believe its currently set at 300ms, so we could do 100ms instead.
