### ISSUE TITLE
Add missing error documentation pages

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#2]
Whenever we render an error page, it links to a documentation page where you can find more information about the error. This pages don't exist yet. That's what this issue is all about.

**Comment by magicmatatjahu** [comment]
I don't know if this issue is still valid and if it will be needed in the new implementation - can you clarify @fmvilas?

**Comment by fmvilas** [comment]
I don't think so as we don't have a database or backend. You can safely close it.
