### ISSUE TITLE
Allow manually setting a JSON Schema URL

### ISSUE THREAD

**Issue by smoya** [asyncapi/studio#207]
#### Reason/Context
Current Studio picks up a JSON Schema from https://github.com/asyncapi/spec-json-schemas based on the `asyncapi` field.
This is valid for most of the users but I wonder if we could allow users to manually enter a URL of a valid JSON Schema (AsyncAPI one) so it can be used for validating.

The reason is that I find it useful for testing changes on the spec that are not yet fully merged. 
I know the use case is very limited, but wondering if we could easily do that.

#### Description
Allow setting an external JSON Schema URL so it can be used for validating the document. It doesn't have to be in the UI, maybe a query parameter such as `?schema=<url>` would be enough.

**Comment by magicmatatjahu** [comment]
Do you wanna validate on different schema by parserJS? Currently parserJS has hardcoded versions of specs and you cannot pass new schema as input to the parser.

**Comment by smoya** [comment]
> Do you wanna validate on different schema by parserJS? Currently parserJS has hardcoded versions of specs and you cannot pass new schema as input to the parser.

I know you load schemas at boot time, but I guess you can also add more schemas to the registry during runtime.

**Comment by magicmatatjahu** [comment]
🤔  We can add new schema to the global object from `@asyncapi/specs`. I will think about it.

**Comment by smoya** [comment]
@magicmatatjahu What do you think about this one? I think it is valid?

**Comment by magicmatatjahu** [comment]
I think it's still relevant :)

**Comment by smoya** [comment]
Still relevant

**Comment by magicmatatjahu** [comment]
@derberg More specifically by Spectral. We can always override some rule from official Spectral's AsyncAPI ruleset in our Parser, it's not a problem.

**Comment by smoya** [comment]
Still relevant
