### ISSUE TITLE
What is next for the visualiser? Need your help!

### ISSUE THREAD

**Issue by boyney123** [asyncapi/studio#213]
![image](https://user-images.githubusercontent.com/3268013/146157471-83c9d3ba-f464-444f-b96e-ecc1a993de8d.png)

A couple of months ago we released the visualiser into the Studio, and from initial feedback, it seems that the community quite like it and find it valuable.

**It would be good to understand what else we can do here to make it better?**

**If you have any ideas or thoughts please share them so we can explore and maybe start building them!**

----

# Ideas

### 1. Allowing the user to create AsyncAPI file from Visualiser (Drag, Drop Nodes and Connect them)

This idea came from @magicmatatjahu but the thought of allowing users to use this tool to build their AsyncAPI file, but using nodes and drag and drop interface.

Users will be able to create `subscriber`, `publisher`, and also `application` nodes and connect them together. When connecting them you will probably be prompted to enter various details about the node type you are connecting/adding.

---

_I will add more ideas as time goes on_

**Comment by jonaslagoni** [comment]
I am just shooting ideas out, no filtration 😆 

- I would love to see it support the visualization of multiple applications, i.e. you can see how applications interact with each other. Related to #195. No idea how to separate such logic and what belongs where, if we compare it to Cupid 🤔 
- Maybe the ability to inspect message payload structures and validation rules 🤔
- When the side menu is clicked, the message/operation gets highlighted or zoomed to.
- Quick action form to send example message to the application 🤔 I.e. a form of simulation (not mocking) of externals interacting with the application.
- When visualizing a single application, maybe show (shadowing) external applications that interact with it.
- Saving placements, i.e. if you restructure the placement of the boxes, it stays that way forever.

Love the creational aspect as you suggested!

**Comment by boyney123** [comment]
Thank you @jonaslagoni 

> Maybe the ability to inspect message payload structures and validation rules

Yeah great idea, at the moment I just added the messages as blocks onto the pub/sub boxes, but yeah the abilty to open them and inspect would be great. Thanks


> When the side menu is clicked, the message/operation gets highlighted or zoomed to.

💯

> Quick action form to send example message to the application

Nice. Do you mean the studio will know how to connect to the applications, and actually start sending real messages/logs etc?

> When visualizing a single application, maybe show (shadowing) external applications that interact with it.

Yeah I like that, I guess it will be easier when we can support multi applications.

> Saving placements, i.e. if you restructure the placement of the boxes, it stays that way forever.

Yeah shouldn't be too hard, guess we can just store them in local storage, thanks!

**Comment by magicmatatjahu** [comment]
@jonaslagoni I like your suggestions, but about multiple application we should have first some logic to handle multiple specs in the Studio like this one idea https://github.com/asyncapi/studio/issues/167 and then use that feature inside Visualiser :)

**Comment by jonaslagoni** [comment]
> Nice. Do you mean the studio will know how to connect to the applications, and actually start sending real messages/logs etc?

Yes!

With the AsyncAPI document, you should have all the information needed (in most cases at least, custom serialization and deserialization functionalities would be hard to support) to send single messages from the browser 🤔

**Comment by magicmatatjahu** [comment]
> With the AsyncAPI document, you should have all the information needed (in most cases at least, custom serialization and deserialization functionalities would be hard to support) to send single messages from the browser 🤔

But also that should be as separate tool, not inside Visualiser, because someone should test app from raw AsyncAPI, not from Visualiser context :)

**Comment by magicmatatjahu** [comment]
Related https://github.com/asyncapi/studio/issues/265
