### ISSUE TITLE
N[String(...)] is not a function on studio.asyncapi.com

### ISSUE THREAD

**Issue by dweber019** [asyncapi/studio#237]
#### Describe the bug
If I copy this snippet from https://github.com/asyncapi/avro-schema-parser
```
asyncapi: 2.2.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: # The following is an Avro schema in YAML format (JSON format is also supported)
          type: record
          name: User
          namespace: com.company
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int
```
into https://studio.asyncapi.com/ I get error `N[String(...)] is not a function`.
If I download the studio locally and past the same snippet, it works.

#### How to Reproduce
see above

#### Expected behavior
No error

**Comment by magicmatatjahu** [comment]
@dweber019 Thanks for issue! 

> If I download the studio locally and past the same snippet, it works.

I confirm, locally it works.... the worst type of error 😅  Probably build process causes some errors when mangling the code. I'll check locally after the build what's going on and let you know! I guess, error is throw by `parserJS` or by parse for `avro`.

**Comment by dweber019** [comment]
Thanks, was just a observation. I'm currently debugging why $ref: <some-url>.avsc doesn't work in backtage.io.
With this error https://discord.com/channels/687207715902193673/687235481154617364/933248339116429312 but still in debug mode ;)

**Comment by magicmatatjahu** [comment]
Fix is on the way https://github.com/asyncapi/studio/pull/238 :)

@dweber019 Without you we would not have been aware of webpack removing support for `avro` and `openapi` - more info in the linked PR. 

May I have a question? From what I can see, you are using Backstage, does AsyncAPI rendering there also throw some kind of error (Backstage uses our component to render AsyncAPI), or is it more of an error with Backstage itself, related to relative $refs?

**Comment by magicmatatjahu** [comment]
@dweber019 You can check preview for changes https://deploy-preview-238--modest-rosalind-098b67.netlify.app/ and your schema works! :)

**Comment by dweber019** [comment]
In backstage currently form what I can tell, the normal avro part works. It's has something to do with the $ref and not being able to download the file in $ref.

I'm currently now in this dependency https://github.com/APIDevTools/json-schema-ref-parser as I think, this component is doing the download.

**Comment by magicmatatjahu** [comment]
> I'm currently now in this dependency https://github.com/APIDevTools/json-schema-ref-parser as I think, this component is doing the download.

Yes, we uses that dependency to make that magic with `$ref` :)

**Comment by dweber019** [comment]
okey will open up an issue at https://github.com/asyncapi/parser-js

**Comment by magicmatatjahu** [comment]
Ok, https://studio.asyncapi.com is updated :)

**Comment by dweber019** [comment]
FYI @magicmatatjahu created issue at https://github.com/backstage/backstage/issues/9040 as it seams there is a polifill issue in backstage.
