### ISSUE TITLE
Tooltip to sidebar icons 

### ISSUE THREAD

**Issue by Samridhi-98** [asyncapi/studio#242]
#### Description
Please try answering a few of those questions
- What changes have to be introduced?
   - Add tooltip to sidebar icons and visualizer icons
- Will this be a breaking change?
   - No 

**Screenshot**

![image](https://user-images.githubusercontent.com/54466041/150631257-4f080ba5-6e8b-4434-b8f6-ae45be88b12f.png)

**Comment by sambhavsaxena** [comment]
I would like to  work with this enhancement
