### ISSUE TITLE
Update studio logo

### ISSUE THREAD

**Issue by mcturco** [asyncapi/studio#289]
#### Reason/Context
As we are beginning the process of rolling out the new brand, I think it would be a good idea to swap the old logo for the new Studio logo as shown below:

![AsyncAPI Studio New Logo](https://user-images.githubusercontent.com/60163079/157478504-02a7938c-2d39-44bb-aaea-497d9ce63f61.jpg)

Figma file: https://www.figma.com/file/XFSjXtubDX5rxpFd7bYyIC/?node-id=2%3A29

You should be able to export the logo from the figma file if you select the `logo-studio` layer from the left sidebar and then click on the **Exports** tab in the top right. Or, download this compressed file: [logo-studio.svg.zip](https://github.com/asyncapi/studio/files/8216312/logo-studio.svg.zip)

We should also update the logo in the loading screen to this new logo as shown here:
![AsyncAPI Studio New Logo Loading](https://user-images.githubusercontent.com/60163079/157480717-80299d2d-003e-4c79-9b22-74c4d52476a6.jpg)

**Comment by magicmatatjahu** [comment]
@mcturco Hi! As I see, people have to create account in the figma and no everyone doesn't have/wants an account there. Maybe you could export and add to the issue zip as attachment with those svg yourself? :)

**Comment by Namyalg** [comment]
I would like to take this up

**Comment by mcturco** [comment]
@Namyalg Awesome! Go for it 😄
