### ISSUE TITLE
Update README with new logo banner

### ISSUE THREAD

**Issue by mcturco** [asyncapi/studio#290]
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://studio.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

**Download the image file:**
[github-repobanner-studio.png.zip](https://github.com/asyncapi/studio/files/8262689/github-repobanner-studio.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

<img width="830" alt="github-repobanner-studio" src="https://user-images.githubusercontent.com/60163079/158605417-f04a7031-18ef-462b-b693-bf6fdd547e43.png">

**Comment by fmvilas** [comment]
Doesn't Studio have its own logo? 🤔 May be worth putting it here instead of this banner?

**Comment by mcturco** [comment]
@fmvilas I was wondering the same thing but wasn't sure... Yeah I guess now that you bring it up, it would be fine since the asyncapi mark is still in the studio logo.

Do we like something like this? Let me know if we should change the description (cc @magicmatatjahu) 

<img width="830" alt="github-repobanner-studiov2" src="https://user-images.githubusercontent.com/60163079/157941392-f9b1c43e-dc25-4f86-bd17-790b2a23d2e5.png">

**Comment by magicmatatjahu** [comment]
@fmvilas @mcturco 

In the description of the repository we have:

```
Visually design your AsyncAPI files and event-driven architecture.
```

We don't only visualize AsyncAPI, but also do other things (that's why we talk also about design of EDA).

**Comment by fmvilas** [comment]
I actually like the second option better 😄 I don't care to scroll tbh.

**Comment by magicmatatjahu** [comment]
We can go with the second option.

**Comment by magicmatatjahu** [comment]
@mcturco I also noticed that we should change the photo in the `og` metadata. Currently the old logo is still there.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/20404945/158606520-601af3ae-0623-445f-9cb3-cd6e3daf32ed.png">

**Comment by mcturco** [comment]
@magicmatatjahu good call! Do you want to open up a separate issue for that?

**Comment by magicmatatjahu** [comment]
@mcturco https://github.com/asyncapi/studio/issues/295 :)
