### ISSUE TITLE
Update OG metadata picture with new logo design

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/studio#295]
This is to replace the old AsyncAPI logo in the OG metadata picture with the new logo that represents the new branding.

Place with `og` media -> https://github.com/asyncapi/studio/blob/master/public/index.html#L19

@mcturco Will post a new picture :)

**Comment by mcturco** [comment]
Here are a few options of images that we could use. Let me know which one we should go with! I personally like option 3 the best

Option 1
![studio-og-image_v1](https://user-images.githubusercontent.com/60163079/158647291-bf6fe4cc-18f9-4aa4-81f3-3e5e7ad50a3e.jpg)

Option 2
![studio-og-image_v2](https://user-images.githubusercontent.com/60163079/158647319-076876eb-daa3-4932-873d-ac0ffe40fa7f.jpg)

Option 3
![studio-og-image_v3](https://user-images.githubusercontent.com/60163079/158647344-a8647fc5-0cc0-42a2-a18a-24ff02f66dbd.jpg)

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/asyncapi/studio/pull/291
