### ISSUE TITLE
DockerHub Image

### ISSUE THREAD

**Issue by galvo** [asyncapi/studio#30]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
It would be beneficial to developers to be able to run this locally and internally within organisations.

- How will this change help?
Pushing the docker image for every new release to docker hub

- What is the motivation? 
Swagger Editor also provides this https://hub.docker.com/r/swaggerapi/swagger-editor/

#### Description
Please try answering few of those questions
- What changes have to be introduced?

On release builds the versioned docker image would be built and pushed to docker hub
- Will this be a breaking change?
no

- How could it be implemented/designed?
as part of the GibHub build

**Comment by derberg** [comment]
moved issue to studio as it will be our new playground and the only official docker image we will provide for the studio, not playground

**Comment by magicmatatjahu** [comment]
I mark this as a long-term issue.
