### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'json')

### ISSUE THREAD

**Issue by andreas-habel** [asyncapi/studio#309]
#### Describe the bug
When working with the studio and pasting/typing the below spec, the site crashes (complete white screen) with the following error in the Browser Console 
```
TypeError: Cannot read properties of null (reading 'json')
    at 2.8b4994d8.chunk.js:2:3484977
    at Array.reduce (<anonymous>)
    at Function.e.parametersToSchema (2.8b4994d8.chunk.js:2:3484898)
    at Ne (2.8b4994d8.chunk.js:2:3514599)
    at sa (2.8b4994d8.chunk.js:2:2790402)
    at Gs (2.8b4994d8.chunk.js:2:2842702)
    at Au (2.8b4994d8.chunk.js:2:2829943)
    at Du (2.8b4994d8.chunk.js:2:2829871)
    at Ou (2.8b4994d8.chunk.js:2:2829734)
    at bu (2.8b4994d8.chunk.js:2:2826700)
cs @ react-dom.production.min.js:216
```

#### How to Reproduce
- Start with a private browsing session and go to https://studio.asyncapi.com/
- Replace the given spec from `Streetlights Kafka API` with

```
asyncapi: 2.3.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  oms/t/xyz/oms/place_orders/{country}:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
    parameters:
      country:
        description: ISO code of the country to place an order for
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

This spec is for sure incomplete, however the studio should not crash...

#### Expected behavior
Show a proper parsing error instead of crashing the studio

---
Tested with MS Edge Version 98.0.1108.56  and Firefox 91.6.1esr

**Comment by magicmatatjahu** [comment]
@andreas-habel Hello! Sorry for such a long delay! I was on a little vacation two weeks ago and when I came in I most likely missed it in the notifications I was looking through while I was gone. However, the problem is fixed and I apologize again!
