### ISSUE TITLE
Run AsyncAPI studio without internet

### ISSUE THREAD

**Issue by antoineApi** [asyncapi/studio#356]
#### Reason/Context
- The current tool retrieves the loader.js file at first launch (from internet) which is then placed in the cache. At next launches, the file is retrieved directly from the cache
- Some users may need to setup the AsyncAPI studio in an environment without internet. In that case, launch is not possible since the loader.js file cannot be retrieved from internet

#### Description
- For the moment, to setup the tool on an environment without internet, the loader.js file has to be placed manually in the \public\js\ folder and \public\index.html file shall be adapted by adding: ` <script src="%PUBLIC_URL%/js/loader.js"></script>` before the ending body markup
- Proposal is to modify the tool to include the loader.js file directly in it to be able to run it without internet and if the internet is available the tool only verifies there isn't a new version of the loader.js file to be used.

**Comment by magicmatatjahu** [comment]
@antoineApi Ok, new version of studio `0.12.4` is out and I was able to fix this problem with the external loader. I check the network tab in the browser and the only sources are from our site (nothing external), so the build itself should already go without internet. Let us know. I am closing the issue, but if there would be any problems then give a comment :)

**Comment by magicmatatjahu** [comment]
Fixed in https://github.com/asyncapi/studio/pull/352
