### ISSUE TITLE
Block Representation for Drag & Drop Project

### ISSUE THREAD

**Issue by wh0sumit** [asyncapi/studio#389]
Since we were planning to create blocks before implementing the coding part on the drag & drop project, we have to discuss the representation/structure of the blocks first. 

Assume that a user adds a block on the visualizer using by dragging and dropping it. After that, the user will be able to edit the block's title, description, and other things. 

so, for changing the title or description of the blocks in the visualizer after adding from the drag & drop panel we have two methods/approaches:

1. We can open an input box in place of the title or description by double-clicking on it,
 and by clicking on the enter button, it will save that particular text to the local storage, 
 so users can change the title, description, and other details of the block by using this approach.

![Blocks Issue](https://user-images.githubusercontent.com/76095902/180159753-9304b73a-c15c-4a93-8e37-b9261dff8e38.png)

2. The second approach I found to be more appropriate in this case was to open a modal for that particular block, rather than opening an input box in place of each title and description.
In this way, the user can change all parameters regarding that particular block in one go. 
By double clicking on the block, we can open the modal for that particular block. 

so these are the approaches I came across, and I'm happy to create example diagrams if needed.

Please guide me through this, and let me know if I am going in the right direction with this.

Let me know, what do you all think about this?

cc: @magicmatatjahu

**Comment by magicmatatjahu** [comment]
@wh0sumit I think that we should go with modal approach. Through the modal we can edit all the information and not just individual ones (as in the case of the first approach) - and also this will be generally easier to implement.
