### ISSUE TITLE
when convention modal shows up it should recommend latest version for convertion

### ISSUE THREAD

**Issue by derberg** [asyncapi/studio#391]
#### Reason/Context

When I paste document in asyncapi version prior 2.4 I get 👇🏼 

![Screenshot 2022-07-21 at 12 53 09](https://user-images.githubusercontent.com/6995927/180197297-45cb6433-41dd-4e40-beb7-202c6bf0ae46.png)

This is super cool, but I'd love to improve my experience, and have the latest version preselected, so by default I'd like to see 👇🏼 

![Screenshot 2022-07-21 at 12 54 26](https://user-images.githubusercontent.com/6995927/180197495-c6fc810c-2b5e-4ce8-b88b-af4fe47b1d5d.png)

This would be uber cool

**Comment by magicmatatjahu** [comment]
It should be changed here https://github.com/asyncapi/studio/blob/master/src/components/Modals/ConvertToLatestModal.tsx#L117

**Comment by nawed2611** [comment]
Hey, Can I work on this issue?

**Comment by magicmatatjahu** [comment]
@nawed2611 Sure :)

**Comment by nawed2611** [comment]
Thanks, Ill work on it

**Comment by nawed2611** [comment]
Made a PR #395
