### ISSUE TITLE
Ask user for reload

### ISSUE THREAD

**Issue by dxps** [asyncapi/studio#393]
#### Reason/Context

While writing your own spec, if - by mistake - you hit your Refresh shortcut, then you loose all you wrote.
And I'm writing this right after I just faced this issue.
There are options to prevent this, some of them described below

#### Description
Here are some options to support this:

1. For preventing the reload to happen without user's consent, there are simple approaches (like [draw.io](https://draw.io) has):
    ![image](https://user-images.githubusercontent.com/14140226/180423226-28edc994-76d9-49c0-9ea2-229152f3a3f4.png)

2. The spec content can also be saved in the browser's local storage.
    - Even if refresh (page reload) happens OR when initially landing in Studio page, User could be asked whether he'd like to load what's locally available.
    - This also covers another potential mistake of closing the tab or the whole browser.

Hope it helps!
Thanks!

**Comment by magicmatatjahu** [comment]
@dxps Hi! Thanks for issue. About notification, it's good idea, but atm studio saves the content to the local storage. By default option to auto save is enabled - you can check if this option is enabled in the terminal by indication `autosave: on`:

![image](https://user-images.githubusercontent.com/20404945/180426813-33d1dd84-92e5-4711-a1a2-a573b29010b0.png)

If you see `autoload: off`, you can go to the options (bottom left corner):

![image](https://user-images.githubusercontent.com/20404945/180426941-4a16ab6d-7d80-4f59-961b-f7d98b43f6bb.png)

and change option to autosave to `on`:

![image](https://user-images.githubusercontent.com/20404945/180427001-effb9be1-e041-4ea1-bcb9-725a91b1d6cf.png)

Let me know if it works for you :)

**Comment by magicmatatjahu** [comment]
EDIT: You have also option to save by keybindings: `ctrl+s` or `cmd+s` (mac).

**Comment by dxps** [comment]
Now, I see that there's something about _localStorage_. But ...
![image](https://user-images.githubusercontent.com/14140226/180426817-aec3b760-29a4-4579-8fbe-3fdc4e38b206.png)

Issues (imho):
1. Seeing that _From localStorage_ label:
    1. I'd expect to get the content from there
    2. OR not even show that specific label when accessing the Studio with `?url=...` since in the latter case might be even misleading.
    3. The right side elipsis (`...`) menu is very handy, but it doesn't give me any option to explicitly load whatever has been saved in the localStorage. I would expect that option as well.
2.  Although it is mentioned _Autosave: On_, I explicitly hit Ctrl + S, got that nice modal confirmation. But after a Tab Refresh/Reload I get back the content referred from `?url=...`. Even just accessing Studio without that query param, I still don't get what I was just writing.

**Comment by dxps** [comment]
@magicmatatjahu 
1. Yes, that _Settings > Auto saving_ is also on in my case as well.
2. Did that explicitly also. See the details posted meanwhile.
Thanks.

**Comment by magicmatatjahu** [comment]
@dxps If you see `from localstorage` label it means that it loads from local storage, but if you load by `url` parameter it shows that it's from url. Of course there's a bug as I see, because editor tries to save value passed by `url` to the localstorage. It should be fixed.

> The right side elipsis (...) menu is very handy, but it doesn't give me any option to explicitly load whatever has been saved in the localStorage. I would expect that option as well.

Yeah it should be implemented, but see my comment above about issue.

> Although it is mentioned Autosave: On, I explicitly hit Ctrl + S, got that nice modal confirmation. But after a Tab Refresh/Reload I get back the content referred from ?url=....

If you hit `ctrl+s` when you have spec loaded from url it saves to the localstorage but if you reloaded with `url` parameter it again fetched data from url and puts in the editor. It works as expected. `url` parameter is nice to showcase for someone or to render only html without editor:

```
https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/master/examples/gitter-streaming.yml&readOnly
```

> Even just accessing Studio without that query param, I still don't get what I was just writing.

Localstorage has value from previous pointed `url` query - see comment above.

I will try implement that new option in editor sidebar (load content from localstorage) and maybe try to improve logic behind `url` parameter, but in the next week :)

**Comment by dxps** [comment]
@magicmatatjahu Yeah, it all makes sense. Thanks for the detailed feedback! :pray:

**Comment by magicmatatjahu** [comment]
@dxps Hi! I created PR with (probably) fixes for above bugs. https://github.com/asyncapi/studio/pull/394 If you want, you can open preview in mentioned PR and let me know what do you think about changes :) I have one UX problem (described in PR), so it will be helpful for me what users think about that.

**Comment by dxps** [comment]
That's pretty nice! :+1: Easily reachable and giving you the feeling you control what's stored locally.
Regarding the PR, I'll read the discussion and maybe comment there.
![image](https://user-images.githubusercontent.com/14140226/180807779-c2bd224e-98d9-4d3e-bfda-5a6873c562b8.png)

**Comment by dxps** [comment]
I played with the preview and it works as expected.
Thanks again! I'll close this issue now.
