### ISSUE TITLE
Use custom modals for "url-mode" confirms.

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/studio#402]
#### Reason/Context

Atm we use native `confirms` "modals" in the `url-mode` of Studio:

![image](https://user-images.githubusercontent.com/20404945/181774501-315f2df0-b812-4d7a-ac76-21dec85b234d.png)

![image](https://user-images.githubusercontent.com/20404945/181774514-b3f3d52c-962f-40b5-b2ea-6c1df4497a67.png)

We should switch to the custom modals, similar to the converter modal.

More info https://github.com/asyncapi/studio/pull/394

cc @mcturco

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by Shurtu-gal** [comment]
@magicmatatjahu Is someone working on this issue?

**Comment by Shurtu-gal** [comment]
@magicmatatjahu Is there any prior design for custom modals?
