### ISSUE TITLE
load spec file via Docker volume

### ISSUE THREAD

**Issue by steevehook** [asyncapi/studio#403]
#### Reason/Context

I want to be able to spin up a docker container that has the `asyncapi.yaml` file either passed as a bind mount or env variable, to be able to load that as soon as the container starts, instead of doing that step manually

#### Description

As a user of this Docker image I wanna be able to reference a Docker volume or env variable and automatically load the configuration on container start.
If this is already present, at least document this feature, I had to clone the project, look it all up and still could not find a proper solution for this

**Comment by magicmatatjahu** [comment]
@steevehook Hi! Thanks for the issue! Atm we don't have such a feature for Docker image. We are open for contributions, so if you wanna contribute, you're welcome :)

**Comment by steevehook** [comment]
Then I guess, PR incoming 😄

**Comment by steevehook** [comment]
That one time when you wanna contribute to Open Source and you got the wrong laptop, or at least that what it says when I try to run `npm run generate:docker`
```
#11 95.83 npm ERR! code 1
#11 95.83 npm ERR! path /node_modules/puppeteer
#11 95.83 npm ERR! command failed
#11 95.83 npm ERR! command sh -c node install.js
#11 95.83 npm ERR! The chromium binary is not available for arm64.
#11 95.83 npm ERR! If you are on Ubuntu, you can install with: 
#11 95.83 npm ERR! 
#11 95.83 npm ERR!  sudo apt install chromium
#11 95.83 npm ERR! 
#11 95.83 npm ERR! 
#11 95.83 npm ERR!  sudo apt install chromium-browser
#11 95.83 npm ERR! 
#11 95.83 npm ERR! ERROR: Failed to set up Chromium r1002410! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
#11 95.83 npm ERR! Error
#11 95.83 npm ERR!     at handleArm64 (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:141:11)
#11 95.83 npm ERR!     at BrowserFetcher.download (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:286:13)
#11 95.83 npm ERR!     at async downloadBrowser (/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:56:5)
#11 95.87 
#11 95.87 npm ERR! A complete log of this run can be found in:
#11 95.87 npm ERR!     /root/.npm/_logs/2022-08-22T10_35_37_212Z-debug.log
```

**Comment by rikuson** [comment]
Hey!!
I've made [PR](https://github.com/asyncapi/studio/pull/433) which solves this issue.

It is not only useful for local development but also hosting own specification.
There's usecase that you want to publish your api specification on S3, or Netlify.
Currently, asyncapi cannot satisfy that usecase.

If this PR is merged, you can do this:
```
$ npm run build
$ rm -r build/docs/asyncapi
$ cp -r ../another/path/to/asyncapi build/docs/
```

@magicmatatjahu 
You were about to help this issue, did you change your mind?
I dedicated my weekend to contribute this project, but there's no any feedback after 3 weeks.

**Comment by magicmatatjahu** [comment]
@rikuson Hi. Sorry for the delay. I'll check it out, don't worry. I've been sick and have to handle all the notifications.
