### ISSUE TITLE
AsyncAPI 2.5.0 pre-release notice

### ISSUE THREAD

**Issue by char0n** [asyncapi/studio#431]
This is a notification for code owners of this repository (@fmvilas @boyney123 @mcturco @magicmatatjahu) to be aware of AsyncAPI 2.5.0 pre-releases:

- https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-spec.2
- https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-spec.3
- https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-spec.4
- https://github.com/asyncapi/spec/releases/tag/v2.5.0
- https://github.com/asyncapi/spec-json-schemas/releases/tag/v2.15.0-next-spec.2
- https://github.com/asyncapi/spec-json-schemas/releases/tag/v2.15.0-next-spec.3
- https://github.com/asyncapi/spec-json-schemas/releases/tag/v3.2.0
- https://github.com/asyncapi/parser-js/releases/tag/v1.17.0-next-spec.1

> Note: if there will be new pre-releases I'll update this issue and add them to above list.

**Comment by char0n** [comment]
Update: Following release candidate of AsyncAPI 2.5.0 spec has been just published:  https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-spec.3

**Comment by char0n** [comment]
Update: Following release candidates of AsyncAPI 2.5.0 spec has been just published:
- https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-spec.4
- https://github.com/asyncapi/spec-json-schemas/releases/tag/v2.15.0-next-spec.3

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/asyncapi/studio/pull/442
