### ISSUE TITLE
Unnecessary assertion since it does not change the type of the expression

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/studio#445]
More info about this issue can be found [here](https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_studio&open=AXy8sl50j5oi-A2Dvomb)

**Comment by dhfherna** [comment]
I would like to work on it. can you assign me?

**Comment by AceTheCreator** [comment]
Hello @dhfherna, we can't assign you an issue. If you are interested in fixing it, please go ahead :)

**Comment by dhfherna** [comment]
Ok @AceTheCreator, I'll create a fork to contribute a solution.

**Comment by magicmatatjahu** [comment]
@dhfherna Do you need help?

**Comment by dhfherna** [comment]
Hi @magicmatatjahu, sorry, i was participating in other repositories. Today i did two PR and i hope you can review.
