### ISSUE TITLE
Extract the assignment of "elementsGrouped[element?.data.groupId]" from this expression.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/studio#446]
More info on this issue can be found [here](https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_studio&open=AXy8sl3Jj5oi-A2DvomZ)

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by magicmatatjahu** [comment]
@nawed2611 Yes :)
