### ISSUE TITLE
Unnecessary assertion since it does not change the type of the expression.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/studio#447]
More info on this issue can be found [here](https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_studio&open=AYNkAOrH1pWMtoDLbyQC)

**Comment by everly-gif** [comment]
Hi, I would like to work on this issue.

**Comment by dhfherna** [comment]
I would like to work on it. can you assign me?
