### ISSUE TITLE
Template Request: { GCP Pub/Sub }

### ISSUE THREAD

**Issue by KarthikBashyam** [asyncapi/studio#457]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by chiragsanghavi** [comment]
It would be great to have PubSub.
