### ISSUE TITLE
update url of studio after making changes

### ISSUE THREAD

**Issue by starlightknown** [asyncapi/studio#463]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
It helps to share the document with others after someone makes changes to the document. Currently the link we share does not direct others to the same document and they still see the unchanged document.
- How will this change help?
This will make sharing easier with doing the base64 encoding and pasting it in url to make it work. 
- What is the motivation? 
This idea came when I was on call with lukasz and I am also working on a tutorial using studio.

**Comment by magicmatatjahu** [comment]
Can you describe it more? Has `base64` to be created and added to the url every time something changes or what?

**Comment by derberg** [comment]
@magicmatatjahu it's about adding `?base64=VALUE` by default to URL, and refresh this value on every change, so anyone can easily copy URL and send it to someone. Just like with https://mermaid-js.github.io/mermaid-live-editor/

yes, asyncapi files are sometimes too large, but then, just detect it and do not do it for large files. Makes sense?

**Comment by magicmatatjahu** [comment]
@derberg question if anyone would like to have automatic `base64` creation. this could be added as an option to the Studio and someone could enable it.

The logic should not be difficult, but the most difficult will probably be with determining whether a given url is the right length because we also have the option of adding to the url the hash of a given element from the template (like `https://studio.asyncapi.com/#server-scram-connections`), and this case would also have to be handled here.

**Comment by derberg** [comment]
@magicmatatjahu sure, just remember Studio is in beta. So nothing blocks us from having `base64` by default.

although better might be to add `share` icon next to `...` menu.

> The logic should not be difficult, but the most difficult will probably be with determining whether a given url is the right length because we also have the option of adding to the url the hash of a given element from the template (like https://studio.asyncapi.com/#server-scram-connections), and this case would also have to be handled here.

I think that it should be simple, and when `#` is there, `base64` should not work. Or, when `base64` is added, `#` is removed. Simple steps, one by one

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by magicmatatjahu** [comment]
@nawed2611 Sure, but please make as Łukasz described his solution in this https://github.com/asyncapi/studio/issues/463#issuecomment-1289032605, ok? :)

**Comment by LakshyaSatpal** [comment]
I believe, this flow will be more uniform for the user since we won't be dealing with adding or removing `#` in the URL. Otherwise, it can be confusing for the user, since URL is being used for both, navigation and saving the changes 🤔

**Comment by magicmatatjahu** [comment]
> wdyt folks? instead of refreshing URL in address bar, have share -> modal with link (and in case we know base64 will be to long and not working in studio, we can show info to the user)

Yeah it will be better :)

**Comment by Shurtu-gal** [comment]
Hey @magicmatatjahu @derberg Can I work upon this?
