### ISSUE TITLE
bug: monaco-yaml cannot fetch http://json-schema.org/draft-07/schema

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/studio#509]
#### Describe the bug

`monaco-yaml` library cannot fetch `http://json-schema.org/draft-07/schema` in the production (in dev env it works, probably problem is with insecure `http` protocol). It produces warning like:

![image](https://user-images.githubusercontent.com/20404945/203981387-0fc4535a-ddba-442a-966c-7255c66e6280.png)

Of course, integration still works and we have features like `autocompletion` etc, but that warning should not shown. 

Interesting thing is that the `json` integration in the monaco can fetch this...

#### How to Reproduce

- go to the https://studio.asyncapi.com/. 
- write any valid schema in yaml format.
- you should see that error.

**Comment by fmvilas** [comment]
Just to clarify: autocompletion doesn't work for me and looks like it's related to this error.
