### ISSUE TITLE
Template Request: rabbitmq

### ISSUE THREAD

**Issue by Aref-alabeid** [asyncapi/studio#525]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by fmvilas** [comment]
> 

@Aref-alabeid would you mind answering the questions above, please? 🙏

**Comment by magicmatatjahu** [comment]
@fmvilas Should we move possibility to create request about template to the `spec` repo? If we will create such a template, it should be also treated as example in the `spec`. WDYT?

**Comment by fmvilas** [comment]
🤔 I don't know. I think it still makes sense to have templates in Studio that will not be in the spec. They serve different purposes. The ones in spec are for learning the spec. The ones in Studio are for getting started and customizing them until you get what you want.
