### ISSUE TITLE
Invalid Websocket template

### ISSUE THREAD

**Issue by domoran** [asyncapi/studio#526]
#### Describe the bug
The Websocket example in the files section of AsyncApi Studio is invalid. 

#### How to Reproduce
Open AsyncAPI Studio, choose "File" and from the example page choose "WebSocket" 

![image](https://user-images.githubusercontent.com/1084805/207142124-c5e5fe94-29c1-467c-bb2f-8fcf4efeb9f7.png)

#### Expected behavior
A valid example.

#### Observed behaviour
Message: Empty or invalid document. Please fix errors/define AsyncAPI document.
with 14 diagnostic messages

**Comment by magicmatatjahu** [comment]
@domoran Thanks for the issue. That template is copied from our official examples and probably we have these same bugs in the `spec` repo. I will fix that!
