### ISSUE TITLE
Add a sidebar for Draggable Blocks

### ISSUE THREAD

**Issue by wh0sumit** [asyncapi/studio#543]
we can add a sidebar to the studio to add blocks that can be draggable and dropped into the visualizer. This sidebar would contain multiple blocks that can be easily dragged and dropped into the visualizer. 

when a block is clicked on the visualizer, the corresponding code for that block should open in the editor, where the properties of the block can be modified for that particular block. In the editor, we have a code to change the properties such as the description of a specific block, message, summary, etc.

we are thinking of creating a modal to add blocks in a draggable manner also, but it’ll reduce the user experience if we drag a block from the modal to the visualizer.

I am looking forward to some discussion around this.
( to learn more about this issue, refer: #265 )

cc- @magicmatatjahu

**Comment by AceTheCreator** [comment]
Hey @wh0sumit, this looks interesting 😄

I'd love to collaborate with you on this :) 

Is there anything available yet concerning the blocks that I can look into?

**Comment by Shurtu-gal** [comment]
@wh0sumit @magicmatatjahu Is someone working on this issue ?
