### ISSUE TITLE
example field is not working using a $ref

### ISSUE THREAD

**Issue by dcorto** [asyncapi/studio#546]
#### Describe the bug

example field is not "populated" on studio.

payload output generated on the studio:

```
{
  "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
  "type": "string"
}
```

when it should be:

```
{
  "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
  "type": "product_stock"
}
```

#### How to Reproduce

```
asyncapi: 2.5.0
info:
  title: Warehouse Domain
  version: 1.0.4
  description: This domain contains warehouse's product stock information
channels:
  product_stock:
    subscribe:
      message:
        $ref: '#/components/messages/product_stock'        
components:
  schemas:
    id:
      type: string
      format: uuid
      description: id in UUIDv4 format
    type:      
      type: string
      description: type of the event          
  messages:
    product_stock:
      summary: lorem ipsum
      description: >-
        lorem ipsum
      payload:
        type: object
        additionalProperties: false
        required:
          - id
          - type
        properties:
          id:
            $ref: '#/components/schemas/id'         
          type:
            $ref: '#/components/schemas/type'
            example: product_stock 
```
#### Expected behavior

The payload output generated on the studio must show:

```
{
  "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
  "type": "product_stock"
}
```

**Comment by magicmatatjahu** [comment]
@dcorto You try to "extend" the object by `$ref` with other keywords in this same level. AsyncAPI doesn't support such a thing and parser "remove" other keywords on this same level as `$ref` keyword.

Please check with this:

```yaml
          type:
            example: product_stock 
```

And you will see:

![image](https://user-images.githubusercontent.com/20404945/212929716-50a47623-27d2-4015-95e4-b6f6674b7f6f.png)


Why do you try to do something like that? Are you have a OpenAPI background? If yes, then AsyncAPI is different in some parts, so please don't treat AsyncAPI structure/possibilities == OpenAPI structure/possibilities.

Any questions?

**Comment by dcorto** [comment]
Hi @magicmatatjahu thanks for the feedback. I get the point :)

But why if i go to Generate code/docs and i choose "HTML website" the generated html, works as I expect on the issue That is why i'm confused. 

Also if I generate the HTML with the docker image asyncapi/generator it's generate as i expect.

Thanks in advance :)

**Comment by magicmatatjahu** [comment]
@dcorto Ahh yes, we have some differences between Studio and other tools. Out core tool - ParserJS - will use another reference library underneath in next major version and now, only Studio uses that new version, another tools uses the old one. In older version of ParserJS, the reference library support such a references, while in the AsyncAPI specification we do not support and this is a "bug" on the side of the tool. If I were you, I would not use such references because they will be "deprecated" in the future :)

**Comment by dcorto** [comment]
All clear! :100: 

Thanks for your quickly responses.

I close the issue
