### ISSUE TITLE
[📑 Docs]: add Studio docs in TOOLS content bucket

### ISSUE THREAD

**Issue by alequetzalli** [asyncapi/studio#552]
### What Dev Docs changes are you proposing?

It's time to add Studio docs to AsyncAPI Docs. To do this, let's first update the documentation inside the actual `studio` repo, and then we'll automate copying over the new docs into the actual website. 

**NOTE**: _Questions about this process should be asked to @derberg, but @Florence-Njeri are most likely able also to help since she did the same automation for the Generator Docs she and pratik wrote during 2022 GSoD_

## Table of contents for new Studio docs
- Introduction
- Usage
- Navigation
- Editor
- HTML Preview
- Blocks visualizer
- Studio Settings

## File names for new Studio Docs

Create individual files for EACH topic outlined in the table of contents. **You should have 7 new files for Studio.**

Ex: `asyncapi.com/docs/tools/studio/introduction`

And your file in this example would be: `introduction.md`

cc @Jagrutiti @magicmatatjahu 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagrutiti** [comment]
This issue awaits review. 

cc: @alequetzalli

**Comment by alequetzalli** [comment]
thanks for the ping, let me double check this week :)

**Comment by Jagrutiti** [comment]
I would like to continue working on this PR once my mentor finds time.
