### ISSUE TITLE
readOnly Query Parameter not hiding text editor

### ISSUE THREAD

**Issue by mlschuh** [asyncapi/studio#591]
#### Describe the bug
The `readOnly` query parameter does not hide the text editor.

#### How to Reproduce
Go to [https://studio.asyncapi.com/?readOnly](https://studio.asyncapi.com/?readOnly) and see that the editor is still visible.

![AsyncAPI Studio Editor Not Hiding](https://user-images.githubusercontent.com/664170/230918930-a87a9408-95c2-48fd-b9b9-735017f87d07.png)

#### Expected behavior
I'd expect it to hide the editor as shown in this PR: https://github.com/asyncapi/studio/pull/113

**Comment by magicmatatjahu** [comment]
@mlschuh Hi! That parametr only works when you also define some AsyncAPI from source, like `url` or `base64` - in other words, `readOnly` doesn't work with doc save in localStorage (in browser).

Try this https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/master/examples/streetlights-kafka.yml&readOnly=true

**Comment by mlschuh** [comment]
Ah, I see. Confirmed working that way on the system I'm building up (using the `url` parameter).

Thank you for clarifying.
