### ISSUE TITLE
Bug :  Restricting users from uploading any file format in the editor

### ISSUE THREAD

**Issue by Sumitmaithani** [asyncapi/studio#623]
#### Describe the bug
Currently, the editor allows users to upload any file format, which poses potential risks to the system's integrity and security. To ensure a safe and consistent user experience, it is necessary to restrict the file formats that can be uploaded in the editor.

#### How to Reproduce
1. Go to http://localhost:3000
2. Import file in editor.
3. Select any file .png, .gif etc.

- Screenshots
 
https://github.com/asyncapi/studio/assets/86047367/d1dc2fcc-176c-40dd-9929-c9914d9bf172

#### Expected behavior
The editor should enforce restrictions on the types of files that users can upload. On which file formats it support required maintainers suggestions. @magicmatatjahu @fmvilas @boyney123

**Comment by Shurtu-gal** [comment]
@Sumitmaithani @fmvilas Can I work on this?

**Comment by fmvilas** [comment]
@Shurtu-gal yeah go ahead 👍

**Comment by Shurtu-gal** [comment]
@fmvilas could you tell which formats do we want to support currently ?
