### ISSUE TITLE
AsyncAPI spec v3 support in Studio

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/studio#641]
### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

### Scope
- [x] https://github.com/asyncapi/studio/issues/746
- [x] https://github.com/asyncapi/studio/issues/793
- [x] https://github.com/asyncapi/converter-js/issues/110 
- [x] https://github.com/asyncapi/parser-js/issues/780
- [x] https://github.com/asyncapi/asyncapi-react/issues/733
- [x] https://github.com/asyncapi/spec-json-schemas/issues/400
- [x] #831
- [x] https://github.com/asyncapi/studio/issues/832
- [x] Update dependencies once they support v3 (mostly automated)

**Comment by fmvilas** [comment]
/progress 90 The only pending thing is [this PR](https://github.com/asyncapi/studio/pull/842) from @Amzani and it's mostly done 🎉
