### ISSUE TITLE
Studio won't load when redirected from Playground

### ISSUE THREAD

**Issue by Hollywood** [asyncapi/studio#648]
#### Describe the bug
When redirected to the Studio using the link `https://studio.asyncapi.com/?redirectedFrom=playground`, the page refuses to load due to an uncaught JS error.

```
Uncaught (in promise) Error: No dispatch method detected, did you embed your app with NiceModal.Provider?
    at m (index.tsx:104:9)
    at _ (index.tsx:225:3)
    at i.<anonymous> (app.service.ts:36:7)
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
```

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

- Go to the link: https://studio.asyncapi.com/?redirectedFrom=playground
- Open dev tools to see the error

![image](https://github.com/asyncapi/studio/assets/7875028/bdabf565-2988-4c4a-9063-c28597ed9269)

#### Expected behavior
I expect the Studio to load instead of remaining on the loading screen.

<img width="1728" alt="image" src="https://github.com/asyncapi/studio/assets/7875028/93711c65-2918-4908-933e-1dc3007dfe53">

**Comment by kaushik-rishi** [comment]
I've encountered the same issue. Looking into it.

**Comment by kaushik-rishi** [comment]
The error is being caused due to this line https://github.com/asyncapi/studio/blob/master/src/services/app.service.ts#L36

I'll try to debug more and propose a fix @Hollywood

**Comment by rukundob451** [comment]
> The error is being caused due to this line https://github.com/asyncapi/studio/blob/master/src/services/app.service.ts#L36
> 
> I'll try to debug more and propose a fix @Hollywood

Nice

**Comment by kaushik-rishi** [comment]
Fixed it. :slightly_smiling_face: 
@Hollywood
