### ISSUE TITLE
Configure the design system to be deployed on the AsyncAPI Netlify account

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#665]
We should use the AsyncAPI Netlify account and decide on a domain where we want to make it available. Dropping some ideas:

* atoms.asyncapi.com
* atoms.studio.asyncapi.com (too long and nested?)
* design-system.asyncapi.com (there may be other design systems for AsyncAPI in the future)
* studio.asyncapi.com/design-system (hard to manage given that it's a separate app from Studio?)

Related to #636

**Comment by Shurtu-gal** [comment]
atoms.asyncapi.com is good, I guess.
