### ISSUE TITLE
Operation Icon component

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#670]
Implement the Operation Icon component as seen in the [Code Editor View of the design](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&t=5t1QnTliI6risXyA-1).

This icon can have 3 variations:

![Captura de pantalla 2023-06-16 a las 8 17 01](https://github.com/asyncapi/studio/assets/242119/8519f578-e9e7-48b5-8fc1-ef01f3afc927)

You can find them here: https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=33%3A1967&t=5t1QnTliI6risXyA-1

Related to #636

**Comment by princerajpoot20** [comment]
I'm working on this 😃

**Comment by princerajpoot20** [comment]
/progress 99 Ready for review : #708
