### ISSUE TITLE
Visual Editor / Code Editor Switch component

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#673]
Implement the Switch component as seen in the [design](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&t=5t1QnTliI6risXyA-1).

![Captura de pantalla 2023-06-16 a las 8 40 52](https://github.com/asyncapi/studio/assets/242119/c958e906-c40d-43ea-9bec-b67bde0d23f3)

**Note:** Do not try to make it a generic Switch component. This one is a very special one with two icons so I would not call it `Switch` but, instead, `EditorSwitch` or something like that to avoid naming collisions with a future Switch component.

Related to #636

**Comment by KhudaDad414** [comment]
/progress 70

The implementation is done. just waiting for https://github.com/asyncapi/studio/issues/666 to use the official tokens instead of hardcoding them in the component.

**Comment by fmvilas** [comment]
You got it :) https://github.com/asyncapi/studio/pull/681

**Comment by KhudaDad414** [comment]
/progress 80

https://github.com/asyncapi/studio/pull/691

**Comment by KhudaDad414** [comment]
/progress 95

PR is ready for review. https://github.com/asyncapi/studio/pull/691
