### ISSUE TITLE
SlideOver component

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#674]
Implement the SlideOver component as seen in the [design](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&t=5t1QnTliI6risXyA-1).

![Captura de pantalla 2023-06-16 a las 8 45 00](https://github.com/asyncapi/studio/assets/242119/dc7e231f-9cc0-4bc4-84c0-ffe587f2468f)

A slide-over component is a menu that flies on top of the existing UI, in this case, coming from the right side of the screen.

**Note:** This is not about implementing the content of the SlideOver component as you can see in the image above. It's about implementing a generic menu that can be closed (with ESC key too) and can contain anything we want. In other words, we pass `{children}` in React.

**Comment by princerajpoot20** [comment]
/progress 10 
Started working on it

**Comment by princerajpoot20** [comment]
/progress 70 Need to do some changes
