### ISSUE TITLE
Create a Markdown template for the ADR

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#676]
I'd suggest we start with something like this: https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md.

Related to #663

**Comment by Amzani** [comment]
@fmvilas I see this as following.

1. We create a ISSUE_TEMPALTE as a form to write the proposal
2. New [ADR]Issue is created
3. Discussion happens via comments
4. Validation / Rejection via comments (at this stage no PR yet)
5. After `/validate-adr` command a PR is auto created with the Markdown file (no need to write it by hand as we already have it) (Or for now we keep it manual)

Then we continue with the validation as you mentioned [here](https://github.com/asyncapi/studio/issues/663)

> Things to validate with the automation:
> 1. If a PR has the kind/adr label, its title has to start with [ADR-xxxx].
> 2. If a PR title starts with [ADR-xxxx], we should add the kind/adr label.
> 3. Once 1 and 2 are met, if a PR is changing multiple files, merge should be blocked.
> 4. Once 1 and 2 are met, if a PR is changing the file of another ADR, merge should be blocked.

WDY ?

**Comment by fmvilas** [comment]
My honest preference is with PRs instead of issues. It's much easier to discuss specific things when you can leave comments on a specific line. Also, validation is implicit (approve the PR) and there would not be any need to remember special commands 🤷

**Comment by Amzani** [comment]
/progress 80

Created [the template](https://github.com/asyncapi/studio/pull/702)

**Comment by Amzani** [comment]
/progress 90

Changed to manual approach for now as the existing tooling is outdated.
