### ISSUE TITLE
Create a GitHub action to automate ADRs validation

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#677]
Related to #663

**Comment by Amzani** [comment]
/progress 5

Starting to work on this

**Comment by Amzani** [comment]
@fmvilas 

> 1. If a PR has the kind/adr label, its title has to start with [ADR-xxxx].
> 2. If a PR title starts with [ADR-xxxx], we should add the kind/adr label.
> 3. Once 1 and 2 are met, if a PR is changing multiple files, merge should be blocked.
> 4. Once 1 and 2 are met, if a PR is changing the file of another ADR, merge should be blocked.

The title validation will conflict with the Lint PR job that recommends to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)

Available types
```
 - feat: A new feature
 - fix: A bug fix
 - docs: Documentation only changes
 - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
 - refactor: A code change that neither fixes a bug nor adds a feature
 - perf: A code change that improves performance
 - test: Adding missing tests or correcting existing tests
 - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
 - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
 - chore: Other changes that don't modify src or test files
 - revert: Reverts a previous commit
 ```

What about using the scope instead `chore(ADR-xxxx): Name of the ADR` (e.g `chore(ADR-0001): use architecture decision records`) ? if we do that we still compliant with the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification) spec. The automation will check that scope is present as well in addition to the exiting lint action.

**Comment by fmvilas** [comment]
I'd not use `chore(ADR-xxxx):` because that means that `ADR-xxxx` is a package on the monorepo, AFAIK. What about `chore: [ADR-xxxx] Title of the ADR`?

**Comment by Amzani** [comment]
/progress 70

Checking title, labels done, figuring our the changed files checks
Testing [here](https://github.com/Amzani/shapeup/blob/main/.github/workflows/check-adr.yml)
Learning: It's quite a challenge to debug Github Actions... 🤯🤯🤯

**Comment by Amzani** [comment]
/progress 95

[PR](https://github.com/asyncapi/studio/pull/713) in review
