### ISSUE TITLE
Add some initial ADRs

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#678]
It would be a good idea to add some initial ADRs. For inspiration:

* #661 (explain why we need a framework and why we chose the one we chose)
* #663 (explain why we decided to use ADRs)
* #636 (explain why we made this repo a monorepo, why we chose a framework over another to implement the components, etc.) There's meat for at least a couple of ADRs in this issue.

Related to #663

**Comment by Amzani** [comment]
/progress 80

Create the `start using ADR` and [Design system ADR](https://github.com/asyncapi/studio/pull/730) 🎨 🚀
