### ISSUE TITLE
Minimal studio App with a working editor and AsyncAPI documentation

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#684]
As part of the discussion in #661, I'm creating this issue to track the migration since it's a huge task.

Related to #661

**Comment by Amzani** [comment]
/progress 10

This is a test

**Comment by Shurtu-gal** [comment]
/progress 20
Figuring out how to add Monaco editor in next.js.

**Comment by Shurtu-gal** [comment]
/progress 40
I've finished the initial setup with the Monaco editor and got a basic skeleton up and running.
Next, got to figure out how to incorporate services.

**Comment by Amzani** [comment]
still relevant

**Comment by Shurtu-gal** [comment]
/progress 40

Some things to note:-
- We are migrating to codemirror now.
- Although lightweight it has many features ( in the form of extensions and plugins which can be added on top of it )
- Would be adding the ADR soon

Things left:-
- Adding menu and AsyncAPI docs

**Comment by KhudaDad414** [comment]
/progress 90

PR is ready for review: https://github.com/asyncapi/studio/pull/1062

Some known issues with current `studio-next` app:
* There is no docker container for it yet.
* tests haven't been ported.
* code generation doesn't work.
* Uses Monaco instead of CodeMirror.
