### ISSUE TITLE
Async API Studio should notify you that changes will be lost when selecting "New File"

### ISSUE THREAD

**Issue by rbhwellframe** [asyncapi/studio#724]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  - Existing behavior is confusing / unexpected
- How will this change help?
  - Users won't accidentally overwrite in progress `async-api.yaml` files
- What is the motivation? 
  - Users won't accidentally overwrite in progress `async-api.yaml` files

#### Description
Please try answering few of those questions
- What changes have to be introduced?
  - Notification / confirmation dialogue on creating a new file
- Will this be a breaking change?
  - Not sure
- How could it be implemented/designed?
  - Notification / confirmation dialogue on creating a new file

Hi,
I wanted to suggest a pop-up dialogue when using AsyncAPI studio. I'm new to using the tool and just encountered something pretty unexpected (in my mind).
1. User launches AsyncAPI studio via command line
  1a. (implied, selects a file using the cli like `asyncapi start studio --file=async-api.yaml`) 
2. User starts working on their new AsyncAPI file
3. User realizes they want to start working on a new file
4. User selects the "New file" pane from the left hand menu in Async API Studio
  4a. 
![image](https://github.com/asyncapi/studio/assets/123779787/bb3bd836-bedc-462a-96d4-605b30c26f13)
5. User selects a template (kafka, in my case if it matters)
6. **Original file is updated to the template selected** e.g. streelights example
7. Control z etc do not work to bring back "original" file

Lost a couple hours of work due to `6.` above, would like to try and prevent others from encountering the same! I understand now that by selecting the file via the cli means that it's really just going to be modifying that file. But the terminology "New File" made me think in the moment that it would be creating a new file. I think a pop up warning that you will lose current changes would be sufficient, since I'm not sure if it's possible to actually create + use a new file in the studio session.

Thanks!

**Comment by nawed2611** [comment]
Hey can i work on this?

**Comment by rbhwellframe** [comment]
I wasn't planning on working on it - been using VSCode in the mean time. I'm not sure if there's a tag of people to "ask for permission" for, but sounds good to me :)

**Comment by KhudaDad414** [comment]
@nawed2611 feel free to open a PR.

**Comment by ashmit-coder** [comment]
Hey @Amzani is this issue still open for PR's?

**Comment by ashmit-coder** [comment]
Hey @KhudaDad414 Will be helpfull if you look into it :)
