### ISSUE TITLE
Enable v3 validation support

### ISSUE THREAD

**Issue by smoya** [asyncapi/studio#742]
Relates to #641

AsyncAPI v3 is still WIP. We are in a very advanced position, however there are still blockers for early releasing something users can use. 
In order to let users test AsyncAPI v3 in advance, I suggest we aim to release a beta version (as a release candidate) version of Studio with the support of the very basics: **validating ASyncAPI v3 documents**. That means no documentation or code generation, no Spectral rules, etc. Just JSON Schema validation. We will add all those features later progressively.

This issue aims to list and track all the work needed to make this version happen.

### Scope
- [x] https://github.com/asyncapi/spec-json-schemas/issues/400
- [x] https://github.com/asyncapi/parser-js/issues/817
- [x] https://github.com/asyncapi/studio/issues/746
- [x] https://github.com/asyncapi/cli/issues/770

##### Studio: Enable validation only

Disable everything except the editor tab and document validation. Use ParserJS rc + JSON Schema rc.

**Comment by Amzani** [comment]
/progress 10

Started to test how to use the new ParserJS with Spec 3.0
