### ISSUE TITLE
Visual Designer: Card component

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#749]
Add the App component into the design system

## Non active
<img width="2150" alt="Screenshot 2023-07-31 at 14 21 37" src="https://github.com/asyncapi/studio/assets/554438/526c3df0-cf1d-4568-bc40-f6b76a33c55b">

## Active
<img width="2138" alt="Screenshot 2023-07-31 at 14 21 44" src="https://github.com/asyncapi/studio/assets/554438/72a6de01-73a2-41b1-8e1c-248ae09fc2c9">

Figma : https://www.figma.com/proto/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=96-2392&scaling=contain&page-id=0%3A1&starting-point-node-id=2%3A2

Related to #748

**Comment by KhudaDad414** [comment]
/progress 10
started working on the issue.

**Comment by KhudaDad414** [comment]
/progress 90
waiting for review.
