### ISSUE TITLE
Visual Designer: Form component

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#752]
Add the form component into the design system

> The Form component represents a document section containing interactive controls for submitting information

<img width="2132" alt="Screenshot 2023-07-31 at 14 56 59" src="https://github.com/asyncapi/studio/assets/554438/4f6f602c-8692-4a7c-b2dd-b6c2d0aa0efe">

### Out of scope 

- The ChipInput component
<img width="1001" alt="Screenshot 2023-07-31 at 15 00 34" src="https://github.com/asyncapi/studio/assets/554438/cbdb64cf-12b3-4ef4-8848-470f4a346bb4">

As part of this PR you might decide to create other components like "DropDown" for instance

Related to #748

**Comment by KhudaDad414** [comment]
This form should be generative right? I mean it should get a json schema and generate a form based on that. plus we could combine the AsyncAPI fields with binding to get a comprehensive list of editable properties.
Imma pick this one up. 😄

**Comment by KhudaDad414** [comment]
/progress 10
tested if https://github.com/rjsf-team/react-jsonschema-form is the right fit and it doesn't seem to be the right solution for us for the following reasons:
* it is UI Framework bound which means no tailwind to customise.
* Our schemas for AsyncAPI file and bindings are not fit for this purpose.
* It can't be used in server components.

**Comment by Amzani** [comment]
@KhudaDad414 I recommend going with the static approach to have more control customisation of form inputs.

**Comment by KhudaDad414** [comment]
/progress 10

Added SingleSelect component.

**Comment by KhudaDad414** [comment]
/progress 15

Added the TextInput component.

**Comment by KhudaDad414** [comment]
/progress 60
The PR is ready for review.

**Comment by KhudaDad414** [comment]
/progress 90
The PR is ready for review.

**Comment by Amzani** [comment]
still relevant.
