### ISSUE TITLE
Visual Designer: ChipInput component

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#753]
> ChipInput allows the users to enter text that can be converted to chips.

<img width="1001" alt="Screenshot 2023-07-31 at 15 00 34" src="https://github.com/asyncapi/studio/assets/554438/7e02fcbf-1396-4f0b-aa27-aa596238189a">

Related to #748

**Comment by princerajpoot20** [comment]
/progress 80
PR ready for review.
