### ISSUE TITLE
Add AsyncAPI 3.0 templates

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#757]
Once #747 is merged we want to add 3.0 templates

<img width="1724" alt="Screenshot 2023-08-02 at 16 00 07" src="https://github.com/asyncapi/studio/assets/554438/c7c8fe56-f823-4b16-919a-33256f86da12">

**Comment by jonaslagoni** [comment]
Any reason we are not using the official list of examples https://github.com/asyncapi/spec/tree/master/examples and just show those? That way they are automatically updated on each release without you haveing to change anything.

**Comment by Amzani** [comment]
I don't know, probably @fmvilas or @magicmatatjahu  have a idea about the why
I like the idea or reusing the examples we already have, or a subset of it.

**Comment by fmvilas** [comment]
Studio should show better crafted examples IMHO. If by "official" you mean the ones in the `spec` repo, those are not really helpful to get you started. Or put it another way, there could be better examples to get you started. So I think Studio should guide you in, for instance, creating a Kafka microservice, or a WebSocket API, etc. More in the line of this: https://www.jetbrains.com/help/idea/new-project-wizard.html#framework-based-project.

**Comment by fmvilas** [comment]
> Looks like somebody needs a hand!

Indeed, Genie 🧞 You're drunk 🍺

**Comment by Amzani** [comment]
Completed
