### ISSUE TITLE
Add code editor to the new NextJS app

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#762]
We want to add a minimal code editor to the new NextJS app.

Why ?
- We want to understand the effort of migrating the current services
- Impact in terms of architecture that can be documented in a new ADR 

Related to #725

**Comment by Shurtu-gal** [comment]
Hey @Amzani

**Comment by Amzani** [comment]
Closing this for now! as studio will need a complete revamp/rewrite with the new DX Working group direction.
