### ISSUE TITLE
Template Request: { Sample Example In Json Format and Account Service}

### ISSUE THREAD

**Issue by macrocks** [asyncapi/studio#778]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement? - I haven't seen a complete example of Async API in JSON format
- How will this change help? - Mulesoft support YAML as well JSON format Async API but there is example anywhere on internet
- What is the motivation?  - JSON friendly example is must in this JSON world.

#### Description
Please try answering few of those questions
- What changes have to be introduced? - sample example in json format
- Will this be a breaking change? - No breaking change
- How could it be implemented/designed? - using JSON format

**Comment by Amzani** [comment]
@macrocks you can convert existing YAML examples in JSON

![Image](https://github.com/asyncapi/studio/assets/554438/9134179d-7bdc-492e-b70e-cacb17bbe8a5)
