### ISSUE TITLE
Studio blows up with some `3.0` document

### ISSUE THREAD

**Issue by derberg** [asyncapi/studio#799]
I've put https://github.com/asyncapi/spec/blob/next-major-spec/examples/streetlights-mqtt.yml in studio

whole app crash, I see white screen

error in browser console:
```
TypeError: Cannot read properties of undefined (reading 'address')
    at Navigation.tsx:79:54
    at Array.map (<anonymous>)
    at Uh (Navigation.tsx:76:50)
    at Sa (react-dom.production.min.js:167:137)
    at Es (react-dom.production.min.js:197:258)
    at Sc (react-dom.production.min.js:292:88)
    at _u (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
```

To open studio again, the only fix is to clear local storage, as of course studio do not want to load due to fact that in local storage we keep the broken file.

---
Broken files should not crash app, I should still be able to see Studio, with proper error info

**Comment by jonaslagoni** [comment]
Ill have a look at this later today

**Comment by derberg** [comment]
just for the record, when I do `asyncapi validate` with latest AsyncAPI CLI - I get info that document is valid

**Comment by jonaslagoni** [comment]
@derberg when I try to use the document you provided, I get no errors? 🤔 
![image](https://github.com/asyncapi/studio/assets/13396189/56214e28-3e40-49d9-9691-ab16c6204057)

**Comment by derberg** [comment]
interesting, happens to be in brave and firefox, and also tried in incognito - the same 🤔

**Comment by jonaslagoni** [comment]
I am using firefox as well 🤔

**Comment by jonaslagoni** [comment]
From the error, it sounds like it detects the document as a v2 🤔 

Cause `Navigation` component is used for that and `Navigationv3` is used for v3 documents 🤔
