### ISSUE TITLE
Not having v3 enabled and pasting v3 documents are semi-broken

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/studio#800]
When I do not have v3 setting enabled and paste a v3 document it does not accurately error out and instead gives a bugged view. 

![image](https://github.com/asyncapi/studio/assets/13396189/08d43ff5-4fdd-40d7-8168-faff9db68e0c)

- It thinks the newest version is 2.6 
- It parses the document as 2.6 but still gives no errors (even when there is)
- Looks like v3 is enabled because of the documentation panel
- And then there is #799

**Comment by Amzani** [comment]
Already fixed
