### ISSUE TITLE
Studio breaks when trying to generate code/document

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/studio#803]
when trying to generate the docs/code, some errors appear in the console
![image (1)](https://github.com/asyncapi/studio/assets/40604284/fb648e8b-3e0a-4762-8301-53f1c7591e6b)

**Comment by Amzani** [comment]
@AceTheCreator could you provide some more details ? what are the steps you did to have theses errors and also you browser details.

**Comment by Amzani** [comment]
Duplicate of [#926](https://github.com/asyncapi/studio/issues/926)
