### ISSUE TITLE
Define the technical solution for PR KPIs

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#805]
Related to #802

**Comment by Amzani** [comment]
/progress 10

Figuring out the technical solution

**Comment by Amzani** [comment]
/progress 15
Exploring https://pullpo.io/app/metrics/

**Comment by Amzani** [comment]
/progress 30

Tested https://pullpo.io/app/metrics/, it's too much of what we want to do for now.
I've started a script that compute the metrics for a given repo including the p25, p50 and p75, still need some refinement.

**Comment by Amzani** [comment]
We are not that bad in studio, I've computed the percentiles for the last merged 100 PRs (excluding automerges and bots).

```
feature_lead_time
P25 11.0 hours, 34.0 minutes, 16.0 seconds
P50 1.0 day, 18.0 hours, 43.0 minutes, 33.0 seconds
P75 4.0 days, 3.0 hours, 4.0 minutes, 11.0 seconds

pr_lead_time metric
P25 11.0 hours, 31.0 minutes, 54.0 seconds
P50 1.0 day, 20.0 hours, 4.0 minutes, 25.0 seconds
P75 6.0 days, 6.0 hours, 14.0 minutes, 1.0 second


time_to_first_review metric
P25 29.0 minutes, 46.0 seconds
P50 2.0 hours, 49.0 minutes, 3.0 seconds
P75 17.0 hours, 43.0 minutes, 45.0 seconds

last_review_to_merge_time metric
P25 3.0 minutes, 20.0 seconds
P50 7.0 minutes, 44.0 seconds
P75 2.0 hours, 33.0 minutes, 13.0 seconds
```

@fmvilas @KhudaDad414 how theses metrics sounds for you ?

**Comment by Amzani** [comment]
/progress 35

Checking metrics validity and visualising them using [chartjs](https://www.chartjs.org/)

**Comment by smoya** [comment]
> creates a slack channel for each PR and this will create a lot of noise for the code owners.

But that's only one part of the product, isn't? Can't we just take the part of the metrics?
The creators of pullpo contacted me offering us a demo session if we want to share our use case and see how they could help. Just in case you are interested.

**Comment by Amzani** [comment]
The solution I have in mind

<img width="964" alt="Screenshot 2023-10-10 at 18 49 41" src="https://github.com/asyncapi/studio/assets/554438/d8bd6ab6-c21a-4a9c-af6e-2e7f2a17f426">



cc @fmvilas @smoya @KhudaDad414

**Comment by Amzani** [comment]
@smoya sure, let's take the opportunity to see the demo

**Comment by Amzani** [comment]
/progress 40

Exploring https://github.com/marketplace/actions/issue-metrics

**Comment by Amzani** [comment]
/progress 50

[Issues metrics](https://github.com/marketplace/actions/issue-metrics) looks great so far, this is an example of generated report https://github.com/shapeitapp/shapeitapp/issues/61
Waiting for review of #815 to check studio metrics of the last month

**Comment by Amzani** [comment]
/progress 100

Decided to go with https://pullpo.io/, we will make a setup in some repositories.
