### ISSUE TITLE
[Studio] Measure AsyncAPI adoption

### ISSUE THREAD

**Issue by smoya** [asyncapi/studio#812]
Related to https://github.com/asyncapi/community/issues/879

## Scope

- [ ] Define metrics to collect
- [ ] Collect metrics in code

**Comment by smoya** [comment]
Something I find challenging is imagining the metrics we want to collect in Studio. CLI is easy; counting each command execution (validate, generate, etc), extract data from documents, etc.
However, the Studio is basically a live editor, where things happen in background, like re-parsing and validating, on every time you update the document.
We might want to set some kind of limitation on those in order to get metrics that make sense to us. Deeply thought... what metrics do we need to ensure we know how users use the Studio?

cc @fmvilas @Amzani

**Comment by smoya** [comment]
Not stale please

cc @Samridhi-98 @peter-rr

**Comment by Vishal2002** [comment]
@smoya We can keep the metrics like  number of document edits and Compexity of document

**Comment by Amzani** [comment]
still relevant
