### ISSUE TITLE
[PITCH]: Support indent level change

### ISSUE THREAD

**Issue by SoulKa** [asyncapi/studio#822]
### Problem

YAML relies on correct indents. When copying parts of the Async API YAML and pasting it into the AsyncAPI Studio, the indent must sometimes be adjusted manually by adding spaces one after the other. This is very cumbersome and error prone.

### Solution

Support indent changes for the selected lines by
 - increasing indent by one level when using `TAB`
 - decreasing indent by one level when using `SHIFT+TAB`

### Rabbit holes

- It must be prevented that the `TAB` changes focus
- The correct indent size must be determined (e.g. 2 spaces)

### Scope

- [ ] Implement key listener on `TAB` and `SHIFT`
- [ ] Add method to get the currently selected line numbers
- [ ] Implement code modifier that adds spaces in the front of each selected line

### Success criteria

- One line can be selected and the indent changes when pressing `TAB` or `SHIFT+TAB`
- Multiple lines can be selected and the indent changes when pressing `TAB` or `SHIFT+TAB`

**Comment by Amzani** [comment]
Thanks for submitting this Issue, however this is already working (I'm tried with Chrome/Firefox/Safari)
https://www.loom.com/share/f99b17706e464e6abfa5b991453af493?sid=f82b3ec5-db25-427f-9c41-376e1b22c9ea
