### ISSUE TITLE
Setup pullpo.io

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#829]
Related to #802

**Comment by Amzani** [comment]
/progress 10

Started the discussion [here](https://github.com/orgs/asyncapi/discussions/920) to get code owners approval

**Comment by Amzani** [comment]
/progress 20

We can set it up in studio and glee, waiting for cli

**Comment by SamarthAroraa** [comment]
Hey @Amzani, can I take this up?

**Comment by Amzani** [comment]
Thanks @SamarthAroraa however this is already in progress and this task doesn't require any code.
For more information check this discussion [here](https://github.com/orgs/asyncapi/discussions/920)

**Comment by Amzani** [comment]
/progress 50 

I got approval from code owners to set it up in cli, glee and studio : https://github.com/orgs/asyncapi/discussions/920
Next: @fmvilas to help with the setup as we need an admin for that.

**Comment by Amzani** [comment]
/progress 100

Done
