### ISSUE TITLE
Make v3 default

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#832]
Currently users needs to enable V3 to use it.
<img width="660" alt="Screenshot 2023-10-26 at 14 31 37" src="https://github.com/asyncapi/studio/assets/554438/52aa315c-96cb-4369-91ee-997c9cdf0df2">

We want to make the `enable v3 support` as default. 

Related to https://github.com/asyncapi/studio/issues/641

**Comment by Shurtu-gal** [comment]
Can I work on this @Amzani ?

**Comment by Amzani** [comment]
@Shurtu-gal sure please take it :)

**Comment by fmvilas** [comment]
Yeah totally. That was done as a temporary thing meanwhile we released v3. It should be completely removed.

**Comment by Shurtu-gal** [comment]
Okay, I will remove it.

**Comment by Shurtu-gal** [comment]
Removed it in [this](https://github.com/asyncapi/studio/pull/841/commits/3bb31164cc8dd88a0ce299ff19f7e4daedf4514a)

cc: @fmvilas @Amzani @KhudaDad414
