### ISSUE TITLE
Inconsistent reporting of "Adheres to" between records of same structure, based on the order of declaration.

### ISSUE THREAD

**Issue by ghuser** [asyncapi/studio#837]
In the following asyncapi document 

```yml
asyncapi: 2.6.0
info:
  title: AsyncAPI
  version: 1.0.0
  description: AsyncAPI
channels:
  example:
    publish:
      message:
        $ref: '#/components/messages/example_message'
components:
  messages:
    example_message:
      name: example_event
      schemaFormat: application/vnd.apache.avro;version=1.9.0
      payload:
        type: record
        name: ParentRecord
        fields:
          - name: r1
            type:
              type: record
              name: Record1
              fields:
                - name: child1
                  type:
                    - 'null'
                    - type: record
                      name: CommonChildRecord
                      fields:
                        - name: field
                          type:
                            type: string
                            minLength: 1
                            maxLength: 256
          - name: r2
            type:
              type: record
              name: Record2
              fields:
                - name: child2
                  type:
                    - 'null'
                    - CommonChildRecord
          - name: r3
            type:
              type: record
              name: Record3
              fields:
                - name: child3
                  type: CommonChildRecord
          - name: r4
            type:
              - 'null'
              - type: record
                name: Record4
                fields:
                  - name: child4
                    type: CommonChildRecord
```

the preview reports the following:

![image](https://github.com/asyncapi/studio/assets/672768/0accdb56-4123-4fec-9af0-41134d095191)

As you can see `r2` is of type `Record2` which equal (structure-wise) to `Record1` (used by `r1`). 
However, the report for `r2` is "Adheres to: Any or null" while the report for `r1` is: "Adheres to Object or null".  

This inconsistent reporting seems to be related with having a nested field (in this case of type `CommonChildRecord`) marked as nullable. But the issue for some reason does not affect the first record.

Now if I make the nested field not nullable, there is no issue, even if the parent is nullable. (rendering of cases of  `r3` and `r4` reports: "Adheres to Object or null")

The above issue also affects the payload in the examples section: see below:

```json
{
  "r1": {
    "child1": {
      "field": "string"
    }
  },
  "r2": {
    "child2": {}
  },
  "r3": {
    "child3": {
      "field": "string"
    }
  },
  "r4": {
    "child4": {
      "field": "string"
    }
  }
}
```

**Comment by Amzani** [comment]
Hi @ghuser I've submitted your issue here https://github.com/asyncapi/asyncapi-react/issues/826 
Thanks

**Comment by ghuser** [comment]
@Amzani 
I have posted a [similar issue](https://github.com/asyncapi/asyncapi-react/issues/857) directly to [asyncapi-react](https://github.com/asyncapi/asyncapi-react/) repository. Should I post similar issued directly to that repo?
