### ISSUE TITLE
Studio renders PUB topics as SUB and SUB topics as PUB

### ISSUE THREAD

**Issue by muhufuk** [asyncapi/studio#845]
#### Describe the bug
Previous version of https://studio.asyncapi.com/ was working as expected. 
Currently even for default project, it renders wrong. Studio renders PUB topics as SUB and SUB topics as PUB

#### How to Reproduce
Paste following url to your browser
https://studio.asyncapi.com/
Please see following image.
![Screenshot 2023-11-08 at 16 42 10](https://github.com/asyncapi/studio/assets/18504514/23633a40-acf8-418c-91b8-c94942617cea)

- Screenshots
- Link to GitHub repository with project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

#### Expected behavior
Studio should show SUB topics as SUB and PUB topics as PUB

**Comment by derberg** [comment]
Thanks, https://github.com/asyncapi/asyncapi-react/pull/795 will soon fix it in react component that after fixing will be updated in studio

**Comment by muhufuk** [comment]
Thank you @derberg 
When I paste completely another API to studio, some times it remembers previous API and somehow It merges them. I am not sure you are also aware of it.

**Comment by derberg** [comment]
@muhufuk better report separate issue for it. I'm not maintainer here in studio, I jumped in only because I noticed the error you reported is related to dependency of studio where I'm a maintainer

**Comment by Amzani** [comment]
Fixed
