### ISSUE TITLE
Studio fails to generate nodejs code 

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/studio#847]
#### Describe the bug
When trying to generate nodejs code using Studio it fails. It returns this error `Internal Generator error Couldn't find server with name 0.` 

And why is it retuning `0` in the server list dropdown instead of the server name

#### How to Reproduce

![AsyncAPI-Studio (1)](https://github.com/asyncapi/studio/assets/40604284/f0922849-ef9e-46af-a8f3-a8b04092263a)

#### Expected behavior
Nodejs code should be generated 

cc @fmvilas @KhudaDad414 @Amzani

**Comment by Amzani** [comment]
@AceTheCreator this is a 2.6.0 AsyncAPI file ? 
As we are now focusing on V3 support I suggest to rethink this feature and support glee instead

**Comment by Amzani** [comment]
Duplicate of [#926](https://github.com/asyncapi/studio/issues/926)
