### ISSUE TITLE
Studio fails to render CommonMarkings

### ISSUE THREAD

**Issue by eelcofolkertsma** [asyncapi/studio#906]
#### Describe the bug
CommonMark in demo document does not render in righthand "human friendly"  rendering of document. 

#### How to Reproduce
Open studio at https://studio.asyncapi.com/#introduction 
Look for /info/description element in title: Streetlights Kafka API (the demo document)
You find Common Mark in lines 8-12:     

### Check out its awesome features:
    * Turn a specific streetlight on/off 🌃  
    * Dim a specific streetlight 😎
    * Receive real-time information about environmental lighting conditions 📈

To the right side bullets and bold are missing       

- Screenshots
- 
![image](https://github.com/asyncapi/studio/assets/71253997/d2c0b322-c115-47ce-9b56-19f359a34d46)

- Link to GitHub repository with project that has issues

#### Expected behavior
Rendered text following CommonMark instructions

**Comment by eelcofolkertsma** [comment]
The issue has been addressed by altering templates in studio, but that is not a real solution!

Original description for streetlights-Kafka template reads quite OK as code (studio left hand) but fails to render in html (studio right hand). This triggered the issue
```
  description: >
    The Smartylighting Streetlights API allows you to remotely manage the city
    lights.
    ### Check out its awesome features:

    * Turn a specific streetlight on/off 🌃  
    * Dim a specific streetlight 😎
    * Receive real-time information about environmental lighting conditions 📈
```

Revised description in current streetlights-Kafka template reads horrible as code (lefthand) but has nice rendering. So do we want to set an example of horrible coding??
`  description: "The Smartylighting Streetlights API allows you to remotely manage the city lights.\n\n### Check out its awesome features:\n\n* Turn a specific streetlight on/off \U0001F303\n* Dim a specific streetlight \U0001F60E\n* Receive real-time information about environmental lighting conditions \U0001F4C8\n"`

**Comment by eelcofolkertsma** [comment]
Solution can be found at editor.swagger pet store example

replace  "description: >"  with "description:|-" and the engine renders as expected

**Comment by KhudaDad414** [comment]
@eelcofolkertsma I see the issue here.  can you open a PR with a fix?
