### ISSUE TITLE
Each channel makes the navigation target in the editor off by 2 lines

### ISSUE THREAD

**Issue by tbaroti** [asyncapi/studio#909]
#### Describe the bug

While using the left navigation pane, each channel present in the file shifts the target navigation line in the editor with +2 lines. Navigating to the first channel works fine, from there on, navigating to other channels will be off an additional +2 lines after each channel. This makes the navigation to other elements (e.g. operations, messages) also off.
This is valid only when using JSON document format (YAML has different issue).

#### How to Reproduce

1. Open the "MQTT" template in Studio (have at least Navigation and Editor panes open)
2. Convert the document to JSON
3. Click on "LIGHTINGMEASURED" channel in Navigation pane -> editor jumps to and highlights "lightingMeasured" - OK
4. Click on "LIGHTTURNON" channel in Navigation pane -> editor jumps to and highlights "lightTurnOn.messages", the line 2 below lightTurnOn - NOK
5. Click on "LIGHTTURNOFF" channel in Navigation pane -> editor jumps to and highlights the line 4 below lightTurnOff - NOK

- Screenshots
![2023-12-23_15h38_24](https://github.com/asyncapi/studio/assets/127620433/0095ca3c-4ad0-4fb3-986b-cd72d99836de)

#### Expected behavior
Clicking on an element in the Navigation pane makes the editor jump to and highlight the line in which the element is defined.

**Comment by KhudaDad414** [comment]
closing in favour of #910 since it seems to be the same issue.
