### ISSUE TITLE
Navigation uses the JSON line numbers in the editor even if the document format is YAML

### ISSUE THREAD

**Issue by tbaroti** [asyncapi/studio#910]
#### Describe the bug

When the Navigation pane on the left gets used, the editor jumps and highlights the line according to the JSON format even if the document format is YAML.

#### How to Reproduce

1. Open the "MQTT" template in Studio (have at least Navigation and Editor panes open)
2. Click on "LIGHTINGMEASURED" channel in Navigation pane -> editor jumps to and highlights a line in the editor that doesn't match with "lightingMeasured"
3. Note the line number
4. Convert the document to JSON
5. Check the line with the previously noted line number -> it matches with "lightingMeasured"

#### Expected behavior
Clicking on an element in the Navigation pane makes the editor jump to and highlight the line in which the element is defined, respecting the current document format.

**Comment by KhudaDad414** [comment]
@tbaroti it seems to be an issue with the parser. opened an issue here: https://github.com/asyncapi/parser-js/issues/936

**Comment by KhudaDad414** [comment]
the underlying issue seems to be the same as #887.
