### ISSUE TITLE
Using local artifactory with schemas causes some issues

### ISSUE THREAD

**Issue by derberg** [asyncapi/studio#917]
#### Describe the bug

I have such document

```yaml
asyncapi: 3.0.0
info:
  title: User Signup API
  version: 1.0.0
  description: The API notifies you whenever a new user signs up in the application.
servers:
  kafkaServer:
    host: test.mykafkacluster.org:8092
    description: Kafka Server
    protocol: kafka
operations:
  onUserSignedUp:
    action: receive
    channel:
      $ref: '#/channels/userSignedUp'
channels:
  userSignedUp:
    description: This channel contains a message per each user who signs up in our application.
    address: user_signedup
    messages:
      userSignedUp:
        $ref: '#/components/messages/userSignedUp'
components:
  messages:
    userSignedUp:
      payload:
        schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
        schema:
          $ref: http://localhost:8080/apis/registry/v2/groups/my-group/artifacts/UserSignedUp
```

And studio points strange issue in not existing line: `42:21 | TypeError: Failed to fetch`

Yes, this is a valid link, I have this resource available. You can easily reproduce it.

Also when I try some different reference, pointing to `https://www.asyncapi.com/resources/casestudies/adeo/CostingRequestPayload.avsc` all is good. Like I don't know, like `localhost` is blocked or something

##### Terminal 1

Start artifactory `docker run -it -p 8080:8080 apicurio/apicurio-registry-mem:2.5.8.Final`

##### Terminal 2

upload schema

```bash
curl \
http://localhost:8080/apis/registry/v2/groups/my-group/artifacts \
-X POST  \
-H "Content-Type: application/json; artifactType=AVRO" \
-H "X-Registry-ArtifactId: UserSignedUp" \
--data @- << EOF
{
  "type": "record",
  "name": "UserSignedUp",
  "namespace": "com.company",
  "doc": "User sign-up information",
  "fields": [
    {
      "name": "userId",
      "type": "int"
    },
    {
      "name": "userEmail",
      "type": "string"
    }
  ]
}
EOF
```

and now you can access schema under: http://localhost:8080/apis/registry/v2/groups/my-group/artifacts/UserSignedUp

quickly checking `curl http://localhost:8080/apis/registry/v2/groups/my-group/artifacts/UserSignedUp --verbose` you can see server returns json with 200 like a charm

but yeah, when you put this link in `$ref` you get the same error as I described.

---

So I thought, maybe it is because of Apicurio, so this is how I confirmed that probably not

1. installed this `npm install -g http-server`
2. created a file with the avro schema mentioned above called `dupa.avro`
3. started server and exposed directory with the file: `http-server /folder/where/avrofile/located/`
4. took `http://127.0.0.1:8080/dupa.avro` and put in AsyncAPI document -> still the same error `TypeError: Failed to fetch`

So I do not think it is a problem of Apicurio sharing some wrong content type or something. Look like there is localhost issue?

**Comment by Amzani** [comment]
@derberg you are using a local studio instance to load your localhost schema ? or using https://studio.asyncapi.com/ ?

**Comment by ayush3160** [comment]
Hi @derberg @Amzani  , I tried to reproduce the error using the http-server method but for me it is working fine. I have attached the screenshot , I think it might be a problem of CORS , Can you just try using `--cors` flag incase of http-server. Let me know If I am missing something would love to solve this bug if it is a bug. 
![Screenshot (66)](https://github.com/asyncapi/studio/assets/89914602/eee5a1d8-8618-4209-b92d-f9a0b846f511)

**Comment by derberg** [comment]
I'm using `https://studio.asyncapi.com/`

**Comment by derberg** [comment]
@ayush3160 but you did not reproduce my environment

- you use studio on localhost, not studio.asyncapi.com
- I cannot test quickly with localhost as I use AsyncAPI CLI, and it has super old version of studio
- `http-server` by default runs with disabled cors, so adding `--cors` just breaks it even more
- when I debug with `http-server` and add `$ref` to studio, there is no fetch request incoming to `http-server`
- also strange that your `$ref` do not point to specific file

in inspect I see
```
Request URL:
http://127.0.0.1:8080/dupa.avro
Referrer Policy:
strict-origin-when-cross-origin
```

Assuming you use netlify, you could do https://github.com/asyncapi/website/blob/master/netlify.toml#L5 

I'm pretty sure that it is CORS on netlify setting, as @ayush3160 proved it works fine on localhost from sources

**Comment by derberg** [comment]
omg it started working when I went into incognito...... 🤦🏼 

normally console was showing `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
and by going to incognito all worked - so yeah some cache issue

now getting also nice error for apicurio:
```
studio.asyncapi.com/:1 Access to fetch at 'http://localhost:8080/apis/registry/v2/groups/my-group/artifacts/UserSignedUp' from origin 'https://studio.asyncapi.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

now I was able to dig in and find proper way to enable cors in apicurio: `docker run --env CORS_ALLOWED_ORIGINS=* -it -p 8080:8080 apicurio/apicurio-registry-mem:2.5.8.Final`

Thanks folks for helping 🙏🏼
