### ISSUE TITLE
Request/reply semantics not clear in the UI

### ISSUE THREAD

**Issue by bjhartin** [asyncapi/studio#919]
#### Describe the bug
I can't get replies to appear in the studio UI (or the generated HTML files - different github repo).

Related: https://github.com/asyncapi/cli/issues/1082

#### How to Reproduce

- Run studio
- Paste this contract in:

```yaml
asyncapi: 3.0.0
info:
  title: Test Contract
  version: 1.0.0
channels:
  PlaceOrder:
    address: 'Place Order'
    messages:
      PlaceOrder:
        $ref: '#/components/messages/NewOrder'
      OrderPlaced:
        $ref: '#/components/messages/OrderPlaced'
operations:
  PlaceOrder:
    action: receive
    channel: 
      $ref: '#/channels/PlaceOrder'
    messages:
      - $ref: '#/components/messages/NewOrder'
    reply:
      messages:
        - $ref: '#/components/messages/OrderPlaced'
      channel:
        $ref: '#/channels/PlaceOrder'
components:
  messages:
    NewOrder:
      payload:
        type: object
    OrderPlaced:
      payload:
        type: object
```

There is no indication that `OrderPlaced` is a reply that the publisher can listen for.

#### Expected behavior
I expected a client of my messaging API to be able to easily see request-reply semantics in the HTML interface (studio or the CLI).

**Comment by KhudaDad414** [comment]
@bjhartin 

There were some errors in your files, after fixing them, I can see the reply in the html of studio.
[Fixed file](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6IDMuMC4wCmluZm86CiAgdGl0bGU6IFRlc3QgQ29udHJhY3QKICB2ZXJzaW9uOiAxLjAuMApjaGFubmVsczoKICBQbGFjZU9yZGVyOgogICAgYWRkcmVzczogJ1BsYWNlIE9yZGVyJwogICAgbWVzc2FnZXM6CiAgICAgIE5ld09yZGVyOgogICAgICAgICRyZWY6ICcjL2NvbXBvbmVudHMvbWVzc2FnZXMvTmV3T3JkZXInCiAgICAgIE9yZGVyUGxhY2VkOgogICAgICAgICRyZWY6ICcjL2NvbXBvbmVudHMvbWVzc2FnZXMvT3JkZXJQbGFjZWQnCm9wZXJhdGlvbnM6CiAgUGxhY2VPcmRlcjoKICAgIGFjdGlvbjogcmVjZWl2ZQogICAgY2hhbm5lbDogCiAgICAgICRyZWY6ICcjL2NoYW5uZWxzL1BsYWNlT3JkZXInCiAgICBtZXNzYWdlczoKICAgICAgLSAkcmVmOiAnIy9jaGFubmVscy9QbGFjZU9yZGVyL21lc3NhZ2VzL05ld09yZGVyJwogICAgcmVwbHk6CiAgICAgIG1lc3NhZ2VzOgogICAgICAgIC0gJHJlZjogJyMvY2hhbm5lbHMvUGxhY2VPcmRlci9tZXNzYWdlcy9PcmRlclBsYWNlZCcKICAgICAgY2hhbm5lbDoKICAgICAgICAkcmVmOiAnIy9jaGFubmVscy9QbGFjZU9yZGVyJwpjb21wb25lbnRzOgogIG1lc3NhZ2VzOgogICAgTmV3T3JkZXI6CiAgICAgIHBheWxvYWQ6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICBPcmRlclBsYWNlZDoKICAgICAgcGF5bG9hZDoKICAgICAgICB0eXBlOiBvYmplY3Q%3D)
<img width="623" alt="Screenshot 2024-01-23 at 11 53 27" src="https://github.com/asyncapi/studio/assets/32505158/56b655c1-5b72-4b69-8131-bf7e42f501ea">

🤔

**Comment by bjhartin** [comment]
@KhudaDad414 Thank you very much!
