### ISSUE TITLE
Disable the generators that are not yet supported in V3

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#979]
Some generators don't support yet V3

- @asyncapi/dotnet-nats-template
- @asyncapi/ts-nats-template
- @asyncapi/python-paho-template
- @asyncapi/nodejs-ws-template
- @asyncapi/java-spring-cloud-stream-template
- @asyncapi/go-watermill-template
- @asyncapi/java-spring-template
- @asyncapi/nodejs-template
- @asyncapi/java-template
- @asyncapi/php-template

## Current behavior

In V3 document ([example](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6IDMuMC4wCmluZm86CiAgdGl0bGU6IEFjY291bnQgU2VydmljZQogIHZlcnNpb246IDEuMC4wCiAgZGVzY3JpcHRpb246IFRoaXMgc2VydmljZSBpcyBpbiBjaGFyZ2Ugb2YgcHJvY2Vzc2luZyB1c2VyIHNpZ251cHMKY2hhbm5lbHM6CiAgdXNlclNpZ25lZHVwOgogICAgYWRkcmVzczogdXNlci9zaWduZWR1cAogICAgbWVzc2FnZXM6CiAgICAgIFVzZXJTaWduZWRVcDoKICAgICAgICAkcmVmOiAnIy9jb21wb25lbnRzL21lc3NhZ2VzL1VzZXJTaWduZWRVcCcKb3BlcmF0aW9uczoKICBzZW5kVXNlclNpZ25lZHVwOgogICAgYWN0aW9uOiBzZW5kCiAgICBjaGFubmVsOgogICAgICAkcmVmOiAnIy9jaGFubmVscy91c2VyU2lnbmVkdXAnCiAgICBtZXNzYWdlczoKICAgICAgLSAkcmVmOiAnIy9jaGFubmVscy91c2VyU2lnbmVkdXAvbWVzc2FnZXMvVXNlclNpZ25lZFVwJwpjb21wb25lbnRzOgogIG1lc3NhZ2VzOgogICAgVXNlclNpZ25lZFVwOgogICAgICBwYXlsb2FkOgogICAgICAgIHR5cGU6IG9iamVjdAogICAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgICBkaXNwbGF5TmFtZToKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgIGRlc2NyaXB0aW9uOiBOYW1lIG9mIHRoZSB1c2VyCiAgICAgICAgICBlbWFpbDoKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgIGZvcm1hdDogZW1haWwKICAgICAgICAgICAgZGVzY3JpcHRpb246IEVtYWlsIG9mIHRoZSB1c2Vy)) not supported generators are displayed even though they are not supported.

<img width="1313" alt="Screenshot 2024-02-27 at 13 31 24" src="https://github.com/asyncapi/studio/assets/554438/8e76c2d6-3c1b-47e7-95a9-74b8c150970e">

## Expected behavior

For a better Developer Experience(DX):

- Disable not supported generators
- Inform the user

<img width="1284" alt="Screenshot 2024-02-27 at 13 38 44" src="https://github.com/asyncapi/studio/assets/554438/d7b3cad0-eb06-455c-be9f-9f311066ed59">

Tracking link: https://github.com/asyncapi/studio/issues/980

Note: Currently there is a bug in the Doc generation for V3, the fix is WIP https://github.com/asyncapi/cli/pull/1200

**Comment by Amzani** [comment]
Sure @devilkiller-ag please take it

**Comment by kalpesh-d** [comment]
Hi @Amzani, I noticed there's no indication of which generators are supported. Do you think it would be a good idea to include an array listing the supported generators?

**Comment by Amzani** [comment]
@kalpesh-d it's in the description

**Comment by hitenvats16** [comment]
Is this issue is fixed now?

**Comment by ashmit-coder** [comment]
> Is this issue is fixed now?

Yes is current being resolved and is near finishing.

**Comment by devilkiller-ag** [comment]
Sorry @Amzani, I got busy with my exams this week, I was planning to resolve this today. @kalpesh-d This issue was assigned to me. You should have asked here before starting your work on this. I am happy that you resolved this issue, but kindly keep in mind to ask the assignee before working on it out of the blue.

**Comment by kalpesh-d** [comment]
@devilkiller-ag, I apologize for not checking with you first.

**Comment by emivalsilvajr** [comment]
Hi, trying to generate docs for v3 using markdown and the studio.asyncapi.com is reporting that is not supported. Is that something that I am missing? 
![Captura de Tela 2024-08-22 às 11 48 38](https://github.com/user-attachments/assets/582ee6d8-b040-4d19-ac5b-991bd214e004)
