### ISSUE TITLE
Divide "Maintainer" role into two categories: Triager and Committer

### ISSUE THREAD

**Issue by quetzalliwrites** [asyncapi/studio#983]
Currently, each AsyncAPI repository has a single level of maintainers, each responsible for various project parts. Their duties range from issue triage to PR (Pull Request) approval and merging. 

We propose introducing two distinct levels of maintainers to _manage an increasing workload_ and _divide responsibilities more clearly_. [Originally proposed and implemented in our `/website` repository](https://github.com/asyncapi/website/issues/2586), we found this change to maintainer roles has expedited work on the website project while facilitating the onboarding of new maintainers. 

> NOTE: Even though AsyncAPI first implemented this concept in the `/website` project, this approach has already been implemented in other OSS communities such as Django, React, Kubernetes, and Node.js.

### 🗳️ `Divide "Maintainer" role into two categories: Triager and Committer`

- **Triager:** Inspired by the Node.js community, triagers assess newly opened issues and pull requests. Assigned the "Triage" role on GitHub, they are responsible for labeling issues and pull requests, commenting on, closing, and reopening them, and assisting users and novice contributors. Triagers aspiring to become committers should collaborate with existing committers to gradually acquire more rights, such as approving and merging simple bug fixes.

- **Committer:** Committers are tasked with approving pull requests and maintaining the project. They receive the "Maintainer" role on GitHub and are responsible for the technical direction of the website, reviewing and approving pull requests, and onboarding new committers and triagers. 
 

Both committers and triagers are included in the `CODEOWNER` file. We would maintain the existing division of duties based on specific topics. As such, triagers may focus exclusively on code-related or documentation-related issues and pull requests.

**Comment by Amzani** [comment]
I love this idea @alequetzalli

**Comment by Amzani** [comment]
How and who will be managing permissions? triager/committer 

(As a current maintainer - I don't have admin access).
 
<img width="1270" alt="Screenshot 2024-02-29 at 14 06 33" src="https://github.com/asyncapi/studio/assets/554438/d011d5a1-06c8-4e42-8c28-02d106b093e1">


cc @alequetzalli @derberg @derberg

**Comment by alequetzalli** [comment]
@Amzani  As for managing permissions, I would assume only the higher level of `commiters`, but unsure of who exactly has those permissions. 🤔  Perhaps the others know more. 

- **committers** will be granted `write` permissions.
- **triagers** will only be granted `read` permissions.
