### ISSUE TITLE
Information bar isn't navigating to the right code block

### ISSUE THREAD

**Issue by Saumya40-codes** [asyncapi/studio#986]
#### Describe the bug

There are sections in information bar in studio which are made to navigate to particular part of the code block and view more information about that, but currently on clicking many of them, it only navigates to the end of the code block.
#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

https://github.com/asyncapi/studio/assets/115284013/53b0df95-522e-4855-8788-5229b7ea2cc3

#### Expected behavior

Expected behaviour will be the navigation on the right part of the code block. For instance on clicking schema, the following part should appear 
![image](https://github.com/asyncapi/studio/assets/115284013/dec0f816-aafa-4f78-83cc-5770c78c956f)

If it is ok, than I will like to work on this bug to solve it.
Thanks!!

**Comment by satishkumarsajjan** [comment]
should this be fixed? if yes, then I can work on it. assign this to me.

**Comment by Amzani** [comment]
Hi @Saumya40-codes please go ahead

**Comment by Amzani** [comment]
Hi @satishkumarsajjan @Saumya40-codes already suggested himself in the description, you can probably help to review his work.
Thanks

**Comment by satishkumarsajjan** [comment]
Oh cool then. @Saumya40-codes let me know if I can be of any help.

**Comment by Saumya40-codes** [comment]
Hey, @Amzani 
I was debugging through the code for this and found that the line 
```
extras.document.getRangeForJsonPath(jsonPath, true);
```
under the function 

```
  getRangeForJsonPath(uri: string, jsonPath: string | Array<string | number>) {
    try {

      const { documents } = documentsState.getState();

      const extras = documents[String(uri)]?.extras;

      if (extras) {
        jsonPath = Array.isArray(jsonPath) ? jsonPath : jsonPath.split('/').map(untilde);

        if (jsonPath[0] === '') jsonPath.shift();

        return extras.document.getRangeForJsonPath(jsonPath, true);
      }
    } catch (err: any) {
      return;
    }
  }
```
in the file *src\services\parser.service.ts* 

is giving wrong range of starting and ending line for the given file path/jsonPath

I'm finding it hard to understand how following getRangeForJsonPath here gives the range of starting and ending part of the line.

![image](https://github.com/asyncapi/studio/assets/115284013/04d44172-1f3b-4038-841c-ec834b437090)

I will be still looking to find the problem here but can you explain how it works internally but? maybe here or slack anywhere it is possible.

for instance when clicked to Schemas the following range appears
![image](https://github.com/asyncapi/studio/assets/115284013/1d2cc0e5-7b63-4f14-b934-28914879e8f9)

@satishkumarsajjan can you help here?

**Comment by satishkumarsajjan** [comment]
I am going through it now.

**Comment by satishkumarsajjan** [comment]
@Saumya40-codes I found out what actually is happening.

This is what we see in the apps editor:(first image)
![Screenshot 2024-03-06 222606](https://github.com/asyncapi/studio/assets/55579930/433bbdc4-6abe-4234-8b1f-f2e2427c5741)

And this is what the function is getting the positions from:(second image)
![Screenshot 2024-03-06 222513](https://github.com/asyncapi/studio/assets/55579930/0b34d4aa-21d6-440a-ba7e-1b5b06b503a5)

so now when i click on "Messages" in nav, I get these as start and end line numbers:(third image)
![Screenshot 2024-03-06 222951](https://github.com/asyncapi/studio/assets/55579930/ab3ecd05-3c46-424e-8794-c721d0d67b9d)

which is actually correct according to second image.
similarly when I click on "Operations" I get these line numbers: (fourth image)
![Screenshot 2024-03-06 223340](https://github.com/asyncapi/studio/assets/55579930/0bb62e37-c022-42aa-b166-5b6a176a391e)

Which is again correct according to second image.

**Comment by satishkumarsajjan** [comment]
In short, we are using json logic to yaml file.

**Comment by satishkumarsajjan** [comment]
My proposed solution: 
```ts
  async scrollTo(jsonPointer: string | Array<string | number>, hash: string) {
    try {
      const range = this.svcs.parserSvc.getRangeForJsonPath(
        'asyncapi',
        jsonPointer
      );
      if (range) {
        await this.scrollToEditorLine(range.start.line + 1);
      }

      await this.scrollToHash(hash);
      this.emitHashChangeEvent(hash);
    } catch (e) {
      console.error(e);
    }
  }
```
this function which is `navigation.service.ts` file, should take one more argument to check the file type and then perform file specific line search logic.

This is what I could come up with. If you have better approach, let's discuss.

**Comment by Vishal2002** [comment]
It is navigating to the correct code block when the document type is json .
![Screenshot 2024-03-06 231612](https://github.com/asyncapi/studio/assets/35897449/dcf8bc6b-3816-4a03-a098-0ae3ed024e82)

**Comment by Saumya40-codes** [comment]
@Vishal2002 @satishkumarsajjan thanks!
I do think we need to do some additional checks based on the file types and currently YAML needs to be handled separately.

**Comment by Vishal2002** [comment]
@Amzani  Can I also work on this issue?

**Comment by Saumya40-codes** [comment]
We will need to iterate through each line of the code anyways isn't it (for .yaml files)?
Is there any better solution

**Comment by Amzani** [comment]
@Vishal2020 sure you can coordinate with @Saumya40-codes and create a PR.

**Comment by Vishal2002** [comment]
@Saumya40-codes It would be great if we could work together on this issue. I think we need to write a separate function which will find the jsonpointer in the `$ref` of that document.

**Comment by Saumya40-codes** [comment]
> @Saumya40-codes It would be great if we could work together on this issue. I think we need to write a separate function which will find the jsonpointer in the `$ref` of that document.

Ok then. But I've already tried to solve this using that way, but it doesn't work in all cases.

**Comment by Saumya40-codes** [comment]
Hey, @Amzani, @princerajpoot20  I've resolved the bug and following is the final output:

https://github.com/asyncapi/studio/assets/115284013/3d95ba5b-6705-4ff9-b395-a005508733e0

The problem as suggest by @Vishal2002 and @satishkumarsajjan (thanks to them !) was that the existing scrollTo function for scrolling to the desirable line was only working when the file type was **JSON** 

---
Now as a fix in *services/navigation.service.ts* file I have made following changes to scrollTo function
```
 async scrollTo(
    jsonPointer: string | Array<string | number>,
    hash: string,
  ) {
    try {
      const doc = this.svcs.editorSvc;
      const docType = doc.value.startsWith('asyncapi') ? 'yaml' : 'json';

      let range;
      if (docType === 'yaml') {
        range = this.svcs.parserSvc.getRangeForYamlPath('asyncapi', jsonPointer);
      } else {
        range = this.svcs.parserSvc.getRangeForJsonPath('asyncapi', jsonPointer);
      }
      
      if (range) {
        await this.scrollToEditorLine(range.start.line);
      }

      await this.scrollToHash(hash);
      this.emitHashChangeEvent(hash);
    } catch (e) {
      console.error(e);
    }
  }
```

Basically, i'm just checking the file type, if it is json im keeping it as it is but if it is **yaml** i've built another method to get the desirable range.

Here is that code(have left the comments)
```
public extractKeys(obj: { [key: string]: any }, keys: Array<string>) {   \\ to get all the keys from our YAML doc
    for (const key in obj) {
      if (obj.hasOwnProperty(key) && typeof key !== 'number' && typeof key !== 'undefined') {
        keys.push(key);
        if (typeof obj[key] === 'object') {
          this.extractKeys(obj[key], keys);
        }
      }
    }
  }

  getRangeForYamlPath(uri: string, jsonPath: string | Array<string | number>) {
    try{
      const { documents } = documentsState.getState();

      const extras = documents[String(uri)]?.extras;

      if (extras) {
        jsonPath = Array.isArray(jsonPath) ? jsonPath : jsonPath.split('/').map(untilde);
        if (jsonPath[0] === '') jsonPath.shift();
        
        const doc = this.svcs.editorSvc;
        const currDoc = doc.value.split(/(\s+|\n)/).filter(Boolean);  \\ filter based on new line and space for instance if value is name: "john" \n age:18      then after this function i'll get ["name:", "john","\n","age:","18:]

        const yamlDoc: object = yaml.load(doc.value) as object; \\ convert our string (taken from this.svcs.editorSvc.value to a yaml object)   Had to use **js-yaml** library for this if any alternative is possible then please suggest

        const keys: Array<string> = [];
        this.extractKeys(yamlDoc, keys); \\ getting all the keys

        \\ below function just loops through the doc and will either add "\n" or the key only

        const propertyNames = currDoc.map((line:string,index:number, res: string[]): string  | null => { 
          
          if (line.includes("\n")) {
            let times = (line.match(/\r\n/g) || []).length;
            return "\n".repeat(times);
          }

          const match = line.match(/^\s*([^:]+)\s*:/);
          if(match && keys.includes(match[1])) {
            return String(match[1]);
          }
          else {
            return null;
          }
        }).filter(Boolean);

        if(!propertyNames) {
          return null;
        }

        let lineCnt = 0;
        let idx = 0; \\ will keep track of the path we want 

       \\ just a simple iteration to get the desired result
        for (let i = 0; i < propertyNames.length; i++) {
          if (propertyNames && String(propertyNames[i]).includes(String(jsonPath[idx]))) {

            let tempIdx = i+1;
            let isRef = false;

            while(tempIdx < propertyNames.length) {    \\ this are for the case when ref is used as the keyword we want might be used here
              if(String(propertyNames[tempIdx]).includes("$ref")) {
                isRef = true;
                break;
              }
              else if(!String(propertyNames[tempIdx]).includes("\n")) {
                break;
              }
              tempIdx++;
            }

            if(isRef){
              continue;
            }
            idx++;

            if (idx >= jsonPath.length) {
              break;
            }
          } else if(propertyNames && String(propertyNames[i]).includes("\n")) {
            lineCnt+= (propertyNames[i]?.split("") || []).length;
          }
        }

        return {
            start: { line: lineCnt+1, character: 0 }, 
            end: { line: lineCnt+1, character: String(propertyNames[lineCnt]).length } 
        };
      }
    }
    catch (err) {
      return err;
    }
  }
```

Might have overdone the things but I tried to keep it as optimized as possible. 
Any inputs @Vishal2002 @satishkumarsajjan ???

**Comment by satishkumarsajjan** [comment]
If it works then raise a PR. Members will review it. The app already uses stoplight lib to parse and get the path. It also does it for yaml, you could have used it and that would have been easy. But if this works then i see no issue. Nice work.

**Comment by Saumya40-codes** [comment]
> If it works then raise a PR. Members will review it. The app already uses stoplight lib to parse and get the path. It also does it for yaml, you could have used it and that would have been easy. But if this works then i see no issue. Nice work.

Oh I wasn't fully aware about that!!
Will migrate the changes accordingly then.
Thanks again!
