### ISSUE TITLE
Adjust the size of the "confirm new file" modal

### ISSUE THREAD

**Issue by koukama** [asyncapi/studio#987]
#### Describe the bug
the size of the modal is quite large 

#### Current behavior 
<img width="1477" alt="Screenshot 2024-03-06 at 12 59 05" src="https://github.com/asyncapi/studio/assets/23728202/45fb8c6f-0572-45fe-a6fa-fc3e8d7fc338">

#### Expected behavior

<img width="1472" alt="Screenshot 2024-03-06 at 12 59 13" src="https://github.com/asyncapi/studio/assets/23728202/a94dc2c6-2119-4357-bcd8-3962b9fe2633">

If you agree, I can fixe it

**Comment by Amzani** [comment]
Hi @koukama please go ahead
