### ISSUE TITLE
Abrupt change in the color of the Navigation sidebar

### ISSUE THREAD

**Issue by helios2003** [asyncapi/studio#989]
#### Describe the bug
The color of the Navigation sidebar changes abruptly from the original color to black when the document is invalid

#### How to Reproduce
- Have the navigation sidebar open and create an invalid document.
- The color of the sidebar suddenly changes to black with the error message.
- Screenshots <br />
Present situation 
<img width="960" alt="image" src="https://github.com/asyncapi/studio/assets/100564488/3efe39e8-4d1f-49fa-9f43-e8b3e136f289"> <br />
Suggested change
<img width="960" alt="image" src="https://github.com/asyncapi/studio/assets/100564488/87529af4-608c-456c-9b1f-dbfd3223b296"> <br />

#### Expected behavior
- Color should remain the same as the original color like how it remains white in the HTML preview as well. As this would better the User Experience.

**Comment by helios2003** [comment]
Maintainers, if you think this is an issue I can fix it.

**Comment by princerajpoot20** [comment]
@helios2003 Thankyou for creating the issue. This seems to be a valid issue. You can go ahead and fix this.
