### ISSUE TITLE
fix padding in some button in design system 

### ISSUE THREAD

**Issue by koukama** [asyncapi/studio#991]
#### Describe the bug
Fixing padding button in "dropDownMenu" and "SlideOver
#### Current behavior
 
<img width="585" alt="Screenshot 2024-03-07 at 10 15 36" src="https://github.com/asyncapi/studio/assets/23728202/bf1f87cc-5ac3-45c0-bf08-659ee634c1bc">
<img width="585" alt="Screenshot 2024-03-07 at 10 15 36" src="https://github.com/asyncapi/studio/assets/23728202/2d199ea0-da99-432b-97c0-4b5df8420939">

#### Expected behavior
 
<img width="689" alt="Screenshot 2024-03-07 at 15 53 15" src="https://github.com/asyncapi/studio/assets/23728202/b7bcc0af-610f-4f3a-9919-3c9cbea3eece">
<img width="719" alt="Screenshot 2024-03-07 at 15 53 04" src="https://github.com/asyncapi/studio/assets/23728202/2d6433ed-3ede-4b15-a44e-ef445568ae37">

I would like to fixe it @princerajpoot20 ?

**Comment by nikhil-3112** [comment]
![Screenshot 2024-03-08 155941](https://github.com/asyncapi/studio/assets/98270496/30174340-705a-4b63-845f-73adabe660f9)
![Screenshot (184)](https://github.com/asyncapi/studio/assets/98270496/b2b1661d-9218-4e22-aa7c-59353b95efa4)


Fixing these issues @koukama

**Comment by nikhil-3112** [comment]
Changed index.css and submitted pull request. Do approve the change and make it result oriented.
@koukama

![Screenshot (184)](https://github.com/asyncapi/studio/assets/98270496/7e8453ad-6796-4c30-b307-47e0531f69b6)
![Screenshot 2024-03-08 155941](https://github.com/asyncapi/studio/assets/98270496/90020ef2-4150-4bb6-a7b8-13ae3b7ac090)
